import type { MirrorCandidate } from "./mirrors";

export const ANIMAL_MIRRORS: MirrorCandidate[] = [
  {
    id: "animal-albatross",
    name: "信天翁",
    kind: "animal",
    vector: { growth: 5, expression: 3, stability: 8, discernment: 6, adaptability: 8 },
    similar: "你与信天翁镜像相似之处，在于能把注意力放到遥远目标上，愿意穿过漫长空中航程，在外界反馈稀少时仍维持方向感和能量分配。",
    different: "真实信天翁依靠翼形与海风完成迁飞；人的长期选择还要处理承诺、资源与同行者意见，不能把耐力等同于永不改道。",
    lesson: "把远目标拆成可观察的补给点，每到一站同时检查体力、信息和关系成本，再决定维持航线还是修正角度。",
    shadow: "若只赞美远行而忽略落地，你可能把求助视为软弱，把迟迟不收束包装成坚持，最终让长期任务失去现实补给。",
    sourceReferences: ["Encyclopaedia Britannica《Albatross》物种条目", "Cornell Lab of Ornithology《Albatrosses》鸟类指南"],
  },
  {
    id: "animal-bottlenose-dolphin",
    name: "宽吻海豚",
    kind: "animal",
    vector: { growth: 6, expression: 8, stability: 5, discernment: 6, adaptability: 9 },
    similar: "你与宽吻海豚镜像相似之处，在于能够在水域变化中快速交换信号，通过群体协作校正方向，并在探索、游戏和任务之间灵活切换。",
    different: "海豚的协同行动由物种感知与生存环境塑造；人的合作还包含价值分歧、角色边界和语言误解，需要主动确认而非凭默契推断。",
    lesson: "在复杂协作中设置短回合反馈：先说观察，再核对理解，最后明确下一次动作，让敏捷反应转化为可追踪的共同进度。",
    shadow: "当刺激过多时，你可能不断连接新线索却不愿结束探索，也可能用热闹互动回避艰难决定，使团队速度快但方向漂移。",
    sourceReferences: ["NOAA Fisheries《Common Bottlenose Dolphin》物种档案", "Smithsonian Ocean《Bottlenose Dolphin》物种介绍"],
  },
  {
    id: "animal-elephant-herd",
    name: "非洲象群",
    kind: "animal",
    vector: { growth: 6, expression: 4, stability: 10, discernment: 6, adaptability: 5 },
    similar: "你与非洲象群镜像相似之处，在于重视长期记忆、照料秩序与群体安全，面对缓慢推进的陆地任务时，常能承接别人暂时放不下的重量。",
    different: "象群的亲缘结构与迁徙需求不同于人类组织；人的责任可以协商、授权和退出，不必用持续承担来证明关系价值。",
    lesson: "为重要责任画出承接边界，标明自己负责、共同负责和需要转交的部分，并提前约定复盘与补位节点。",
    shadow: "若稳定被误解为不能动摇，你可能把疲惫隐藏在可靠形象后，直到负担超过容量才突然撤退，让自己和群体都措手不及。",
    sourceReferences: ["Smithsonian's National Zoo《African Elephant》物种档案", "IUCN Red List《Loxodonta africana》评估条目"],
  },
  {
    id: "animal-giant-pacific-octopus",
    name: "巨型太平洋章鱼",
    kind: "animal",
    vector: { growth: 2, expression: 7, stability: 2, discernment: 7, adaptability: 7 },
    similar: "你与巨型太平洋章鱼镜像相似之处，在于独居探索时仍能快速读取环境，遇到障碍会改变路径、工具或呈现方式，以高警觉保留撤离空间。",
    different: "章鱼的变色、触腕与洞穴生活是身体适应；人的变化会被伙伴解释为态度和承诺，因此还需要说明意图与连续性。",
    lesson: "保留多条解决路径时，同时写下不变目标和切换条件，让别人看见你是在调整方法，而不是随时放弃共同约定。",
    shadow: "若把灵活推到极端，你可能在每次压力出现时更换身份或策略，短期脱困却难以累积信任，也很少停下来辨认真正需求。",
    sourceReferences: ["Monterey Bay Aquarium《Giant Pacific Octopus》动物指南", "Smithsonian Ocean《Giant Pacific Octopus》物种介绍"],
  },
  {
    id: "animal-gray-wolf",
    name: "灰狼",
    kind: "animal",
    vector: { growth: 7, expression: 6, stability: 7, discernment: 7, adaptability: 6 },
    similar: "你与灰狼镜像相似之处，在于进入群体任务后会敏锐留意角色位置和陆地风险，既能快速跟进行动，也愿意为共同目标保持高警觉。",
    different: "狼群并非人类组织的权力寓言；人的角色来自能力、授权和讨论，不能把关系简化为固定等级或本能服从。",
    lesson: "协作启动前说清目标、决定权和求助信号，行动中用事实更新分工，不让未说出口的地位猜测替代工作协议。",
    shadow: "当安全感不足时，你可能把不同意见看成忠诚测试，过度巡查伙伴反应；这种警觉会侵蚀本来想保护的合作关系。",
    sourceReferences: ["Smithsonian's National Zoo《Gray Wolf》物种档案", "U.S. Fish & Wildlife Service《Gray Wolf》物种档案"],
  },
  {
    id: "animal-green-sea-turtle",
    name: "绿海龟",
    kind: "animal",
    vector: { growth: 5, expression: 2, stability: 9, discernment: 5, adaptability: 6 },
    similar: "你与绿海龟镜像相似之处，在于能接受缓慢但持续的水域行程，不依赖密集回应确认价值，并会凭长期线索回到真正重要的方向。",
    different: "海龟的洄游由生物机制和栖息地连接；人的归属感会随经历改变，旧方向值得核验，而不是因为熟悉就自动正确。",
    lesson: "为长期项目保留一项稳定指标和一项开放指标：前者守住承诺，后者允许新信息改变路线与完成方式。",
    shadow: "低警觉带来从容，也可能让风险信号被延后处理；若只按旧节奏前进，你会错过环境已经改变的证据和必要协商。",
    sourceReferences: ["NOAA Fisheries《Green Turtle》物种档案", "IUCN Red List《Chelonia mydas》评估条目"],
  },
  {
    id: "animal-honeybee-colony",
    name: "蜜蜂群落",
    kind: "animal",
    vector: { growth: 8, expression: 8, stability: 6, discernment: 6, adaptability: 5 },
    similar: "你与蜜蜂群落镜像相似之处，在于进入群体节奏后能快速感知任务缺口，把空中移动、信息传递和重复劳动连接成可见成果。",
    different: "蜂群分工依靠物种机制，人类成员却有多重身份和个人选择；高效率不能代替知情、同意与公平分配。",
    lesson: "每次集体冲刺前确认产出、工作量和退出条件，给协调劳动留下记录，使贡献不因过于顺手而变成隐形义务。",
    shadow: "持续高警觉会让你对空档产生焦虑，习惯立刻补位；久而久之，别人难以练习承担，你也可能只剩忙碌而失去判断。",
    sourceReferences: ["Smithsonian Institution《Honey Bees》教育资料", "Encyclopaedia Britannica《Honeybee》物种条目"],
  },
  {
    id: "animal-manatee",
    name: "西印度海牛",
    kind: "animal",
    vector: { growth: 3, expression: 2, stability: 9, discernment: 4, adaptability: 6 },
    similar: "你与西印度海牛镜像相似之处，在于偏好低警觉、缓慢而稳定的水域节奏，能在不过度争夺注意的情况下维持自身位置和温和存在感。",
    different: "海牛的低速生活受身体与栖息环境影响；人的温和不意味着必须接受侵入，边界仍要通过语言和行动明确表达。",
    lesson: "在不想提高音量时提高边界清晰度，用具体时间、可接受范围和后续动作说不，让温和与自我保护同时成立。",
    shadow: "如果把避免冲突当成唯一安全策略，你可能过晚回应明显问题，让小摩擦积累成无法绕开的阻塞，也使需求长期不可见。",
    sourceReferences: ["U.S. Fish & Wildlife Service《West Indian Manatee》物种档案", "Smithsonian's National Zoo《Manatee》物种介绍"],
  },
  {
    id: "animal-meerkat",
    name: "狐獴",
    kind: "animal",
    vector: { growth: 6, expression: 6, stability: 7, discernment: 9, adaptability: 6 },
    similar: "你与狐獴镜像相似之处，在于群体行动时会快速扫描陆地环境，愿意承担观察与提醒职责，并把高警觉转成伙伴可用的预警。",
    different: "狐獴的放哨行为服务于野外生存；人的风险判断还需区分事实、概率与情绪，提醒不等于替所有人决定。",
    lesson: "报告风险时分三栏写下已发生、可能发生和建议动作，再邀请伙伴补充证据，避免警报直接升级成控制。",
    shadow: "当观察职责变成身份核心，你可能无法真正休息，并把平静误判为疏忽；过密提示会降低团队对重要信号的敏感度。",
    sourceReferences: ["Smithsonian's National Zoo《Meerkat》物种档案", "San Diego Zoo Wildlife Alliance《Meerkat》动物档案"],
  },
  {
    id: "animal-orca-pod",
    name: "虎鲸家族群",
    kind: "animal",
    vector: { growth: 7, expression: 7, stability: 8, discernment: 8, adaptability: 7 },
    similar: "你与虎鲸家族群镜像相似之处，在于能在广阔水域中维持紧密协作，把快速判断、经验传递和群体照料组合成稳定行动。",
    different: "虎鲸群体的生态传统不能直接套用于家庭或团队；人的亲密关系需要容纳退出、跨群体连接与个人目标。",
    lesson: "把共同经验整理为可讨论的方法，而非不可质疑的家规；保留传承价值，也为新成员和新环境设置修订入口。",
    shadow: "高凝聚力若失去开放性，容易把外部观点当作威胁，让保护传统滑向排斥差异，成员也会因害怕离群而压住真实判断。",
    sourceReferences: ["NOAA Fisheries《Killer Whale》物种档案", "Center for Whale Research《Orca Survey》研究项目资料"],
  },
  {
    id: "animal-peregrine-falcon",
    name: "游隼",
    kind: "animal",
    vector: { growth: 2, expression: 7, stability: 2, discernment: 7, adaptability: 7 },
    similar: "你与游隼镜像相似之处，在于独居观察时能迅速收束注意，在空中机会窗口出现后快速行动，并以高警觉不断校准目标位置。",
    different: "游隼俯冲依赖身体结构和猎食需求；人的果断选择还需承担信息不足、他人影响与可逆性判断。",
    lesson: "为关键决定预设起飞条件、停止条件和复盘时间，使速度服务于清楚标准，而不是用行动冲淡犹豫。",
    shadow: "若沉迷于捕捉短暂窗口，你可能在目标尚未值得投入时过早加速，也可能忽略落地后的维护、解释与恢复。",
    sourceReferences: ["Cornell Lab of Ornithology《Peregrine Falcon》鸟类指南", "U.S. Fish & Wildlife Service《Peregrine Falcon》物种资料"],
  },
  {
    id: "animal-red-crowned-crane",
    name: "丹顶鹤",
    kind: "animal",
    vector: { growth: 5, expression: 5, stability: 8, discernment: 8, adaptability: 5 },
    similar: "你与丹顶鹤镜像相似之处，在于能在空中迁移与湿地停留之间保持节奏，对关系距离和环境变化有持续观察，并愿意缓慢建立稳定配合。",
    different: "鹤类结群、配对和迁徙受生态条件影响；人的关系承诺包含谈判和成长，不能把稳定理解为静止不变。",
    lesson: "定期讨论关系中的距离、协作与个人空间，把默认默契变成双方都能修改的约定，让稳定具有更新能力。",
    shadow: "若过度珍视端正与秩序，你可能压低笨拙尝试和即时情绪；表面平稳之下，真正分歧会因长期未说而变硬。",
    sourceReferences: ["International Crane Foundation《Red-crowned Crane》物种档案", "BirdLife International《Red-crowned Crane》物种资料"],
  },
  {
    id: "animal-sloth",
    name: "三趾树懒",
    kind: "animal",
    vector: { growth: 4, expression: 1, stability: 9, discernment: 5, adaptability: 4 },
    similar: "你与三趾树懒镜像相似之处，在于独居时能够接受缓慢节奏，在陆地树冠环境中减少无谓消耗，并用低警觉保留稳定专注。",
    different: "树懒的低代谢是生理适应；人的慢可能来自深思、疲惫或回避，三者需要不同处理，不能一概美化为从容。",
    lesson: "为慢速任务设一个最小可见进度，并记录身体恢复与回避信号，确认节奏是在保护质量还是推迟必要面对。",
    shadow: "当节能成为默认理由，你可能错过需要及时回应的人和事；长期没有外部校验，也会让熟悉路径悄悄缩小选择。",
    sourceReferences: ["Smithsonian's National Zoo《Sloth》物种档案", "Encyclopaedia Britannica《Sloth》物种条目"],
  },
  {
    id: "animal-snow-leopard",
    name: "雪豹",
    kind: "animal",
    vector: { growth: 5, expression: 2, stability: 6, discernment: 9, adaptability: 7 },
    similar: "你与雪豹镜像相似之处，在于独居环境中仍能保持高警觉，面对崎岖陆地地形会谨慎选择路线，并在真正需要时快速完成跨越。",
    different: "雪豹的隐蔽行动服务于高山生存；人的低可见度可能保护专注，也可能让协作者缺少必要信息和回应入口。",
    lesson: "把不想公开的过程与必须共享的节点分开，至少让相关人知道目标、风险和下一次更新时间，减少无谓猜测。",
    shadow: "若把独立等同于不留下踪迹，你可能在困难累积时才暴露问题；他人无法及时支持，也可能把沉默理解成拒绝合作。",
    sourceReferences: ["Smithsonian's National Zoo《Snow Leopard》物种档案", "Snow Leopard Trust《About Snow Leopards》物种资料"],
  },
  {
    id: "animal-wild-goose-flock",
    name: "鸿雁雁阵",
    kind: "animal",
    vector: { growth: 8, expression: 5, stability: 7, discernment: 6, adaptability: 7 },
    similar: "你与鸿雁雁阵镜像相似之处，在于群体远行时能快速响应空中阻力变化，愿意轮换位置，并通过持续联系保持共同方向。",
    different: "雁阵的飞行收益来自空气动力与迁徙本能；人的轮值还需要公平标准、能力匹配和对隐性劳动的承认。",
    lesson: "为长周期合作设计领航、跟随和休整三种位置，约定何时轮换以及怎样表达掉队，让协作不依赖少数人硬撑。",
    shadow: "如果过度在意不脱离队形，你可能压住合理异议，也可能在已经需要休整时继续跟随，最终用耗竭换取表面一致。",
    sourceReferences: ["Cornell Lab of Ornithology《Greater White-fronted Goose》鸟类指南", "BirdLife International《Swan Goose》物种资料"],
  },
];
