import type { MirrorCandidate } from "./mirrors";

export const HISTORICAL_MIRRORS: MirrorCandidate[] = [
  {
    id: "historical-confucius",
    name: "孔子",
    kind: "historical",
    vector: { growth: 9, expression: 7, stability: 8, discernment: 8, adaptability: 6 },
    similar: "你与孔子这一历史镜像可比较之处，是愿意把个人学习放进长期实践，通过提问、整理与因人调整，使知识逐步变成可以共同使用的秩序。",
    different: "孔子面对的是春秋时代的礼制与政治网络；你所在的制度、职业和关系结构不同，不能把古代角色规范直接当成今日答案。",
    lesson: "选一个反复出现的现实问题，连续四周记录行动、反馈与修正，把抽象原则放进具体场景检验，而非停在赞同层面。",
    shadow: "若过度依赖既有秩序，你可能把形式完整误认为关系真实，也可能用教导替代倾听，使本来促进成长的标准变成距离。",
    sourceReferences: ["孔子弟子及再传弟子编《论语》", "《史记·孔子世家》"],
  },
  {
    id: "historical-florence-nightingale",
    name: "弗洛伦斯·南丁格尔",
    kind: "historical",
    vector: { growth: 8, expression: 6, stability: 9, discernment: 9, adaptability: 7 },
    similar: "你与南丁格尔这一历史镜像可比较之处，是能把照料愿望转化为记录、标准和组织改进，不只处理眼前困难，也追问环境如何系统性影响结果。",
    different: "她的工作处于十九世纪医疗与公共卫生变革中；你的专业权限和证据条件不同，关怀不能替代训练、流程与责任边界。",
    lesson: "面对重复问题，先建立一页最小记录表，连续收集事实，再用一次小规模调整验证效果，让善意获得可复查的执行路径。",
    shadow: "当使命感压过身体和协作边界，你可能把休息看成背离责任，也可能因标准过高而减少伙伴参与，最终让改进只靠个人支撑。",
    sourceReferences: ["Florence Nightingale《Notes on Nursing》", "The National Archives (UK)《Florence Nightingale》馆藏指南"],
  },
  {
    id: "historical-gandhi",
    name: "莫罕达斯·甘地",
    kind: "historical",
    vector: { growth: 8, expression: 8, stability: 8, discernment: 7, adaptability: 7 },
    similar: "你与甘地这一历史镜像可比较之处，是倾向让公开立场与日常实践相互校验，并相信持续、自我约束的行动能够逐步改变更大的关系结构。",
    different: "甘地身处殖民统治、民族运动与复杂争议之中；你的处境不应借用其道德权威简化，历史人物的局限也需要保留审视。",
    lesson: "把一个重要主张改写成自己先能履行的三项行为，并设置他人可质询的证据点，使立场不靠姿态而靠连续实践获得重量。",
    shadow: "若把自我约束推成普遍要求，你可能忽略不同人的资源、身体和选择权；道德确信也可能遮住行动造成的真实压力。",
    sourceReferences: ["Gandhi Heritage Portal《The Story of My Experiments with Truth》", "Collected Works of Mahatma Gandhi，印度政府出版档案"],
  },
  {
    id: "historical-helen-keller",
    name: "海伦·凯勒",
    kind: "historical",
    vector: { growth: 10, expression: 8, stability: 7, discernment: 7, adaptability: 9 },
    similar: "你与海伦·凯勒这一历史镜像可比较之处，是愿意寻找替代性的感知和表达通道，把受限条件转化为长期学习问题，并持续扩大与世界连接的方式。",
    different: "她的感官经历、教育支持和公共身份具有独特历史条件；你的困难不能类比其身体经验，也不应借励志叙事抹去具体资源差异。",
    lesson: "当常用路径失效时，列出还可使用的感官、工具和协作者，设计一个低门槛实验，用实际反馈寻找第二条进入问题的通道。",
    shadow: "如果只允许自己呈现克服与进步，你可能隐藏疲惫和依赖需要，也会不自觉用个人韧性替制度缺口承担责任。",
    sourceReferences: ["Helen Keller《The Story of My Life》", "American Foundation for the Blind《Helen Keller Biography》"],
  },
  {
    id: "historical-li-qingzhao",
    name: "李清照",
    kind: "historical",
    vector: { growth: 6, expression: 10, stability: 4, discernment: 8, adaptability: 7 },
    similar: "你与李清照这一历史镜像可比较之处，是能细辨经验中的层次，并把迁移、失落与日常感受转化成有结构的表达，使私人观察具有持续辨识度。",
    different: "她的创作处于宋代文人传统、战乱迁徙和性别限制中；你的表达媒介与社会位置不同，不能把作品风格简化为固定性格。",
    lesson: "选择一段尚未整理的经历，分别写事实、感受和仍未回答的问题，再决定适合公开、留存或暂缓的表达边界。",
    shadow: "当辨识力持续向内收紧，你可能反复雕琢感受而迟迟不行动，也可能让审美标准压住粗糙但必要的求助和沟通。",
    sourceReferences: ["李清照《金石录后序》", "《宋史·李格非传》及相关记载"],
  },
  {
    id: "historical-marie-curie",
    name: "玛丽·居里",
    kind: "historical",
    vector: { growth: 9, expression: 5, stability: 9, discernment: 10, adaptability: 7 },
    similar: "你与玛丽·居里这一历史镜像可比较之处，是面对不确定材料时愿意长期重复验证，把微弱差异当成可追踪证据，并让结论接受公开检验。",
    different: "她的研究依赖特定实验条件、合作网络与时代科学环境；你的坚持若缺少相应方法和安全规范，不能仅凭热情类比科研成就。",
    lesson: "为一个重要判断建立证据日志，区分观察、推断和反例，每次更新只改变有新证据支持的部分，保留可复现步骤。",
    shadow: "若把耐力视为唯一美德，你可能忽视身体代价、协作贡献和停止条件；长期投入也会因沉没成本而变得难以重新评估。",
    sourceReferences: ["Nobel Prize《Marie Curie – Biographical》", "Marie Curie《Pierre Curie》传记及自传笔记"],
  },
  {
    id: "historical-nelson-mandela",
    name: "纳尔逊·曼德拉",
    kind: "historical",
    vector: { growth: 9, expression: 8, stability: 9, discernment: 8, adaptability: 8 },
    similar: "你与曼德拉这一历史镜像可比较之处，是能在长期压力中保存目标，同时根据现实条件调整行动方式，并尝试把个人立场转成可持续的公共协商。",
    different: "他面对的是南非种族隔离制度与国家转型，选择伴随巨大集体代价和历史争议；日常冲突不能轻率套用这一尺度。",
    lesson: "在僵局中分别写下不可放弃的原则、可以协商的路径和需要共同验证的事实，先寻找一项不伤害底线的下一步。",
    shadow: "如果把和解理解为尽快消除张力，你可能过早压下损害与责任；若只守象征位置，也可能让真实修复缺少制度动作。",
    sourceReferences: ["Nelson Mandela Foundation《Timeline》", "Nelson Mandela《Long Walk to Freedom》"],
  },
  {
    id: "historical-sima-guang",
    name: "司马光",
    kind: "historical",
    vector: { growth: 6, expression: 5, stability: 9, discernment: 10, adaptability: 5 },
    similar: "你与司马光这一历史镜像可比较之处，是重视材料次序、判断标准和长期编纂，愿意让复杂事件经过比对后再进入可供后来者使用的叙述。",
    different: "他的史学与政治判断嵌入北宋制度和士大夫立场；你的信息环境不同，编排事实本身也需要接受来源偏差检查。",
    lesson: "处理争议材料时先列时间线和来源等级，再把事实、解释与价值判断分层书写，让读者看见结论是怎样形成的。",
    shadow: "若过度相信完整体系，你可能压低暂时无法归类的新证据，也可能把维护标准变成拒绝试验，使判断稳定却逐渐失去适应。",
    sourceReferences: ["司马光《资治通鉴》", "《宋史·司马光传》"],
  },
  {
    id: "historical-sima-qian",
    name: "司马迁",
    kind: "historical",
    vector: { growth: 8, expression: 9, stability: 8, discernment: 9, adaptability: 7 },
    similar: "你与司马迁这一历史镜像可比较之处，是愿意跨越单一立场搜集人物和事件材料，在个人困境中仍尝试完成一项具有长期结构的表达工程。",
    different: "他的写作与遭遇属于汉代史官制度和个人生命处境；你的项目不应借其苦难来证明价值，完成方式可以包含保护与协作。",
    lesson: "为长期作品建立人物、事件、证据和疑问四类索引，每完成一个单元就核对缺席视角，避免宏大目标掩盖材料偏差。",
    shadow: "当完成使命成为唯一叙事，你可能把损耗当成必要代价，也可能因作品意义重大而不愿缩小范围，最终失去可持续节奏。",
    sourceReferences: ["司马迁《史记·太史公自序》", "《汉书·司马迁传》"],
  },
  {
    id: "historical-su-shi",
    name: "苏轼",
    kind: "historical",
    vector: { growth: 8, expression: 10, stability: 5, discernment: 7, adaptability: 9 },
    similar: "你与苏轼这一历史镜像可比较之处，是在环境转换中仍能寻找表达、实践和人际连接的新接口，把挫折经验转化为多种可继续使用的能力。",
    different: "他的仕途、贬谪与文学活动受北宋政治和文人网络塑造；你的变动条件不同，豁达形象也不等于没有失落或风险。",
    lesson: "每遇一次计划外变化，分别保留一项原目标、发展一项新用途、联系一位现实伙伴，让适应不只是情绪安慰。",
    shadow: "若善于转化成为惯性，你可能太快把损失写成收获，跳过哀伤、申诉和边界修复，也让别人低估你需要支持。",
    sourceReferences: ["苏轼《东坡全集》", "《宋史·苏轼传》"],
  },
  {
    id: "historical-tao-yuanming",
    name: "陶渊明",
    kind: "historical",
    vector: { growth: 7, expression: 7, stability: 8, discernment: 9, adaptability: 5 },
    similar: "你与陶渊明这一历史镜像可比较之处，是会认真衡量外部职位与内在原则的交换成本，并尝试让生活方式和价值判断保持更高一致。",
    different: "他的仕隐选择发生在东晋社会、家计与文人传统之中；你的工作退出、收入和照料责任需要独立核算，不能浪漫化退隐。",
    lesson: "写下一个不愿交换的原则、三个现实成本和两种折中方案，用具体数字与关系影响检验价值选择是否可持续。",
    shadow: "若把纯粹感置于所有协商之前，你可能过早退出仍可改善的关系，也可能让家人或伙伴承担未被讨论的现实代价。",
    sourceReferences: ["陶渊明《归去来兮辞》及诗文", "《晋书·陶潜传》"],
  },
  {
    id: "historical-wang-yangming",
    name: "王阳明",
    kind: "historical",
    vector: { growth: 9, expression: 7, stability: 7, discernment: 9, adaptability: 8 },
    similar: "你与王阳明这一历史镜像可比较之处，是不满足于把理解停在概念上，而会追问判断怎样进入行动，并在实际困难中反过来校正认识。",
    different: "他的思想、军政实践和明代学术语境彼此交织；今日个人成长不能忽略专业规范、权力关系和行动对他人的后果。",
    lesson: "选择一个自认明白却反复做不到的问题，把下一步缩成二十分钟内可完成的动作，做完后记录认知被事实修正的地方。",
    shadow: "如果强调内在判断而缺少外部检验，你可能把确信当成充分证据；行动速度也可能越过协商、能力边界和受影响者声音。",
    sourceReferences: ["王守仁《传习录》", "《明史·王守仁传》"],
  },
  {
    id: "historical-xu-xiake",
    name: "徐霞客",
    kind: "historical",
    vector: { growth: 9, expression: 6, stability: 5, discernment: 9, adaptability: 10 },
    similar: "你与徐霞客这一历史镜像可比较之处，是愿意离开二手判断，通过实地移动、连续观察和修正记录，把探索变成别人能够复查的材料。",
    different: "他的旅行条件、地理知识和明代道路环境具有历史特殊性；今日探索还涉及安全、许可和对当地社区的尊重。",
    lesson: "为一次探索建立路线、观察、证据和修正四栏记录，每天标出一项原判断被现场改变的地方，避免只收集印证。",
    shadow: "若把未知持续当成召唤，你可能不断扩展边界却难以完成整理；个人耐受力也会遮住安全准备和同行者承受的风险。",
    sourceReferences: ["徐弘祖《徐霞客游记》", "钱谦益《徐霞客传》"],
  },
  {
    id: "historical-xuanzang",
    name: "玄奘",
    kind: "historical",
    vector: { growth: 10, expression: 6, stability: 8, discernment: 9, adaptability: 9 },
    similar: "你与玄奘这一历史镜像可比较之处，是面对知识版本差异时愿意追溯来源，承受长期学习与迁移成本，并把所得系统整理为可传播成果。",
    different: "他的行旅、译经和宗教目标处在唐代跨区域交流中；你的知识问题通常有更安全的验证路径，不需要复制极端风险。",
    lesson: "遇到关键概念分歧时，找到两个一手来源和一个权威注解，列出译法或定义差异，再说明自己采用版本及限制。",
    shadow: "如果追源愿望没有停止条件，你可能把所有行动推迟到完全理解之后，也可能因投入巨大而难以承认某条路线已经不再必要。",
    sourceReferences: ["玄奘、辩机《大唐西域记》", "慧立、彦悰《大唐大慈恩寺三藏法师传》"],
  },
  {
    id: "historical-zhang-qian",
    name: "张骞",
    kind: "historical",
    vector: { growth: 9, expression: 6, stability: 9, discernment: 7, adaptability: 9 },
    similar: "你与张骞这一历史镜像可比较之处，是在目标长期受阻时仍能保留任务线索，进入陌生环境后学习新关系，并把见闻转成后续协作依据。",
    different: "他的出使处于汉代国家战略与跨区域政治中，风险和权力尺度远超日常项目；坚持不应被用来否定合理撤退。",
    lesson: "给长期任务设置原目标、替代成果和撤退标准三条线，即使主目标延迟，也持续沉淀地图、联系人和已验证信息。",
    shadow: "若只以抵达原终点评价自己，你可能低估途中形成的有效成果，也会因为承诺过重而忽略环境已经改变的撤退证据。",
    sourceReferences: ["《史记·大宛列传》", "《汉书·张骞李广利传》"],
  },
];
