import type { MirrorCandidate } from "./mirrors";

export type MovieCharacterRecord = MirrorCandidate & {
  kind: "movie";
  filmTitle: string;
  characterName: string;
  region: "中国大陆" | "中国香港" | "亚洲" | "欧美";
  stage: "instinct" | "current" | "growth";
  coreDrive: string;
  actionStyle: string;
  stressResponse: string;
  relationshipStyle: string;
  talentExpression: string;
  blindSpot: string;
  turningPoint: string;
  matureArc: string;
  shadowArc: string;
};

type MovieCharacterInput = Omit<MovieCharacterRecord, "kind" | "name">;

function movie(record: MovieCharacterInput): MovieCharacterRecord {
  return {
    ...record,
    name: `${record.filmTitle}·${record.characterName}`,
    kind: "movie",
  };
}

export const MOVIE_CHARACTERS: MovieCharacterRecord[] = [
  movie({
    id: "movie-cn-ne-zha",
    filmTitle: "哪吒之魔童降世",
    characterName: "哪吒",
    region: "中国大陆",
    stage: "instinct",
    vector: { growth: 8, expression: 10, stability: 3, discernment: 5, adaptability: 7 },
    coreDrive: "核心推动力来自对自我定义权的强烈维护，不愿让外部判断替自己决定价值。",
    actionStyle: "先以直接而高能量的方式突破限制，再从结果中寻找真正能够承担的方向。",
    stressResponse: "压力上升时容易用攻击性姿态保护脆弱，把被误解的痛感转成更大的外在声量。",
    relationshipStyle: "对信任对象极为投入，却常用试探和反向表达确认关系是否会在困难时留下。",
    talentExpression: "擅长把不被看好的能量集中成行动，在停滞场域里创造突然启动的可能。",
    blindSpot: "容易把所有边界都理解为否定，因此错过其中真正用于保护自己与他人的部分。",
    turningPoint: "真正的转折发生在他开始区分别人贴上的定义与自己选择的责任，不再只靠反抗证明存在。",
    matureArc: "成熟方向是保留锋芒，同时让力量接受目标、后果和关系边界的共同校准。",
    shadowArc: "阴影方向是持续依赖冲撞获得存在感，使每次靠近都先变成一场忠诚测试。",
    similar: "当五维特征呈现高表达、高成长而稳定度较低时，你与哪吒的镜像相似在于启动能量很强，也格外在意行动是否出自自己选择，而非别人预设。",
    different: "角色冲突被电影高度集中；现实中的评价通常来自多方关系，你仍有时间澄清、试验和逐步修复。",
    lesson: "把想反抗的限制拆成伤害、规则和误解三类，只对真正不合理的部分用力，并为行动写明希望保护的对象。",
    shadow: "若把强度当成真诚的唯一证明，你可能不断制造对抗来确认自主，最终让可协商的问题也失去缓冲空间。",
    sourceReferences: ["电影《哪吒之魔童降世》（2019）"],
  }),
  movie({
    id: "movie-cn-zhang-mazi",
    filmTitle: "让子弹飞",
    characterName: "张麻子",
    region: "中国大陆",
    stage: "instinct",
    vector: { growth: 6, expression: 9, stability: 5, discernment: 9, adaptability: 8 },
    coreDrive: "核心推动力是夺回行动规则的解释权，并让隐藏的利益结构在公开碰撞中显形。",
    actionStyle: "习惯以快速试探、反向布局和公开姿态同时推进，使对手难以只按表面信息判断。",
    stressResponse: "遭遇压制时会提高博弈强度，把不确定转成对局，但也可能过度依赖胜负逻辑。",
    relationshipStyle: "重视伙伴在关键节点的选择，信任常通过共同冒险建立，而不是通过温和确认累积。",
    talentExpression: "能够迅速辨认权力与语言之间的裂缝，并把复杂局面转成可执行的突破口。",
    blindSpot: "容易低估长期治理与细部照料，把赢得局面误当成已经建立了新的稳定秩序。",
    turningPoint: "转折在于他必须面对战术胜利和共同目标并非同一件事，伙伴意愿也不能完全纳入布局。",
    matureArc: "成熟方向是让敏锐判断服务于透明规则，并在胜负之外建设可持续的协作机制。",
    shadowArc: "阴影方向是把所有关系都变成棋局，最终只能相信可控制的反应而无法接住真实差异。",
    similar: "当辨识与表达维度同时较高时，你与张麻子的镜像相似在于能快速看见话语背后的结构，也敢在窗口出现时打破表面平衡，迫使问题进入公开层面。",
    different: "银幕中的博弈通过强烈冲突压缩呈现；现实协作更需要程序、证据和受影响者的持续参与。",
    lesson: "在揭示问题后补上一张建设清单，分别写明新规则、执行者和复盘点，避免突破只留下短暂震动。",
    shadow: "如果每个分歧都被解释成阵营斗争，你会越来越擅长赢得回合，却越来越难获得可以纠错的真诚伙伴。",
    sourceReferences: ["电影《让子弹飞》（2010）"],
  }),
  movie({
    id: "movie-cn-ma-youtie",
    filmTitle: "隐入尘烟",
    characterName: "马有铁",
    region: "中国大陆",
    stage: "instinct",
    vector: { growth: 4, expression: 2, stability: 10, discernment: 5, adaptability: 6 },
    coreDrive: "核心推动力是用持续劳作维持基本生活和关系尊严，不愿让困顿彻底夺走照料能力。",
    actionStyle: "依靠缓慢、重复而具体的劳动推进，很少用宏大表达替代眼前必须完成的事情。",
    stressResponse: "压力来临时倾向继续承担并缩小个人需要，直到可用资源被消耗得几乎没有余地。",
    relationshipStyle: "通过细小照料和共同劳动建立亲近，表达含蓄，却会把对方处境纳入自己的日常安排。",
    talentExpression: "能够从有限条件中组织出稳定节奏，让微小资源经过耐心使用产生真实支撑。",
    blindSpot: "容易把承受视为唯一可行方式，缺少向外请求、议价和拒绝不公平安排的通道。",
    turningPoint: "转折来自关系使劳动不再只是生存动作，他开始看见共同生活也包含被照料与被珍惜。",
    matureArc: "成熟方向是保留朴实承担，同时让自身需要进入关系和资源分配的可见范围。",
    shadowArc: "阴影方向是把沉默承受固化成身份，使不公长期存在而自己越来越缺少选择。",
    similar: "当稳定维度突出而表达维度较低时，你与马有铁的镜像相似在于更相信长期行动而非响亮承诺，也能在资源有限时守住日常责任和关系温度。",
    different: "角色处于特定乡土与经济条件中；你的资源网络可能更多，持续承担之前仍可主动寻找制度与伙伴支持。",
    lesson: "把每周承担列成必须、自选和被默认三类，至少从最后一类中提出一项协商，让可靠不再等于无条件接受。",
    shadow: "若所有需要都被压回沉默，你可能在别人眼中一直能够应付，直到损耗已无法通过一次休息或求助修复。",
    sourceReferences: ["电影《隐入尘烟》（2022）"],
  }),
  movie({
    id: "movie-cn-liu-peiqiang",
    filmTitle: "流浪地球",
    characterName: "刘培强",
    region: "中国大陆",
    stage: "current",
    vector: { growth: 7, expression: 5, stability: 9, discernment: 8, adaptability: 7 },
    coreDrive: "核心推动力是把个人选择放进更长时间尺度，守住家人责任与集体任务之间的连接。",
    actionStyle: "先依赖训练、程序和远程信息稳定局面，在关键节点才集中承担不可回避的决定。",
    stressResponse: "压力升高时会收紧情感表达并优先执行任务，容易让亲近者只看见距离而看不见牵挂。",
    relationshipStyle: "通过长期负责表达关心，却不总能及时解释缺席、牺牲和决定对关系造成的影响。",
    talentExpression: "擅长在高风险系统中保持任务意识，把分散信息收束成具有时间顺序的行动判断。",
    blindSpot: "容易默认重大责任能够替代关系沟通，低估未被说明的选择会给家人留下何种解释空白。",
    turningPoint: "转折在于他必须把专业职责和个人情感放进同一个决定，而不能继续让两者彼此隔离。",
    matureArc: "成熟方向是让担当不仅体现在结果，也体现在提前说明、共同选择和后续关系修复。",
    shadowArc: "阴影方向是不断用更大任务证明责任感，却让最重要的人长期无法参与真实决定。",
    similar: "当稳定、辨识和成长维度较高时，你与刘培强的镜像相似在于能够在复杂系统里维持长期目标，并愿意为超出个人得失的责任持续投入。",
    different: "电影把选择放在极端系统风险中；现实多数责任可以分段讨论，也应给相关者更多知情和共同决策空间。",
    lesson: "重大任务开始前同时写工作承诺与关系承诺，明确更新时间、可求助节点和变更条件，不让沉默替你解释责任。",
    shadow: "若总在最后关头才表达在意，你可能获得任务完成，却让关系长期承受无法参与、无法确认和无法修复的距离。",
    sourceReferences: ["电影《流浪地球》（2019）"],
  }),
  movie({
    id: "movie-cn-cheng-dongqing",
    filmTitle: "中国合伙人",
    characterName: "成东青",
    region: "中国大陆",
    stage: "current",
    vector: { growth: 9, expression: 7, stability: 7, discernment: 6, adaptability: 8 },
    coreDrive: "核心推动力是通过持续学习和可见成果改写自我评价，并建立不再轻易被否定的位置。",
    actionStyle: "从低门槛实践开始，借重复训练积累信心，再把个人方法逐步扩展为团队事业。",
    stressResponse: "受到轻视时会加倍投入并追求证明，压力可能转化成控制节奏和压缩伙伴差异。",
    relationshipStyle: "珍视共同奋斗形成的连接，但在事业放大后容易把旧情义与新治理混在同一套期待中。",
    talentExpression: "擅长把个人失败经验整理成他人可学习的方法，并用真切感受建立表达穿透力。",
    blindSpot: "容易用曾经的匮乏解释当下决定，忽略规模变化已经要求新的规则和权力约束。",
    turningPoint: "转折来自成功不再只是个人翻身，他必须学习让伙伴关系经得起利益、角色和方向分歧。",
    matureArc: "成熟方向是把韧性升级为治理能力，让共同愿景通过公开规则而不是创始情谊延续。",
    shadowArc: "阴影方向是永远向过去的否定者证明自己，使事业增长却无法带来真正的内在安定。",
    similar: "当成长与适应维度突出时，你与成东青的镜像相似在于愿意从不占优势的位置反复练习，并能把亲身受挫转化成可传播、可带动他人的经验。",
    different: "角色的创业路径受特定年代和行业机会影响；你的成长不必复制扩张逻辑，成功标准也可由自己重新界定。",
    lesson: "每当项目扩大一级，就重写一次决定权、收益和退出机制，使个人韧性不被组织默认成所有问题的无限补丁。",
    shadow: "若持续靠证明驱动，你可能无法享受已取得的成果，也会把伙伴的不同意见听成对过去脆弱自己的再次否定。",
    sourceReferences: ["电影《中国合伙人》（2013）"],
  }),
  movie({
    id: "movie-cn-jingqiu",
    filmTitle: "山楂树之恋",
    characterName: "静秋",
    region: "中国大陆",
    stage: "current",
    vector: { growth: 7, expression: 4, stability: 7, discernment: 6, adaptability: 6 },
    coreDrive: "核心推动力是在外部评价严格的环境里守住情感真实，同时保护家庭与个人未来的安全。",
    actionStyle: "行动谨慎，习惯先观察后靠近，通过小幅确认逐步建立对关系和环境的信任。",
    stressResponse: "面对不确定时会压低直接需求，反复评估可能后果，因此容易让选择长期停在等待状态。",
    relationshipStyle: "珍视纯粹、可靠的陪伴，但不熟悉把担心和期待直接放进双方可以讨论的语言。",
    talentExpression: "能够敏锐感受关系中的细微变化，并以克制方式保存认真、责任和对他人的体谅。",
    blindSpot: "容易把谨慎等同于不添麻烦，因而让自身边界和需要依赖对方猜测而不是清楚表达。",
    turningPoint: "转折在于她逐渐承认情感选择也属于自己的人生，而不只是等待外部条件允许的事情。",
    matureArc: "成熟方向是保留慎重，同时练习主动询问、明确选择和承受关系中必要的不确定。",
    shadowArc: "阴影方向是为了避免风险持续缩小表达，最后让真正重要的关系只剩未说出口的可能。",
    similar: "当成长、稳定居中而表达相对克制时，你与静秋的镜像相似在于不会轻易承诺，却会认真对待每一次靠近，并持续评估选择对家庭和未来的影响。",
    different: "角色受特定年代的社会规范约束；你通常拥有更多沟通渠道和选择空间，可以更主动地确认事实与边界。",
    lesson: "遇到重要关系选择时，用一句需要、一句担心和一个具体请求开启讨论，不让所有谨慎都变成独自推演。",
    shadow: "如果等待绝对安全才行动，你可能把时间交给外部环境决定，也让对方无法分辨你的沉默是拒绝还是珍惜。",
    sourceReferences: ["电影《山楂树之恋》（2010）"],
  }),
  movie({
    id: "movie-cn-jia-xiaoling",
    filmTitle: "你好，李焕英",
    characterName: "贾晓玲",
    region: "中国大陆",
    stage: "growth",
    vector: { growth: 9, expression: 8, stability: 5, discernment: 6, adaptability: 8 },
    coreDrive: "核心推动力是修补自我亏欠感，希望通过让母亲满意来证明自己曾经带来过足够的幸福。",
    actionStyle: "会用热情、幽默和密集行动改变场域，遇到阻力时不断寻找新的方式促成理想结果。",
    stressResponse: "内疚升高时容易接管他人的选择，把补偿性行动当作唯一出口，不愿停下听见真实需要。",
    relationshipStyle: "情感投入真挚而直接，但有时会把自己认定的好结果放在对方自主表达之前。",
    talentExpression: "擅长用亲近感和喜剧能量降低距离，让难以表达的爱获得被看见和被回应的机会。",
    blindSpot: "容易认为只有变得足够优秀才配接受爱，因而低估关系中早已存在的接纳与双向照料。",
    turningPoint: "转折来自她发现修补关系并不等于重写他人的人生，而是重新看见对方真实选择和对自己的爱。",
    matureArc: "成熟方向是把内疚转成当下可持续的陪伴，同时允许自己在不完美中接受关系支持。",
    shadowArc: "阴影方向是不断制造补偿任务，让爱被成绩化，自己也永远无法抵达足够好的终点。",
    similar: "当表达、成长和适应维度较高时，你与贾晓玲的镜像相似在于会主动创造连接，也愿意为了重要的人快速调整方案，把情感化成可见行动。",
    different: "电影借特殊结构集中呈现代际理解；现实修复无法重来，只能依靠当下询问、倾听和持续相处逐步发生。",
    lesson: "把想补偿的冲动改成一次真实询问，先了解对方此刻最需要什么，再选择自己能稳定做到而非最戏剧化的行动。",
    shadow: "若爱始终通过自责驱动，你可能越努力越难接收已有的接纳，也会让亲近者承担证明你无须内疚的额外任务。",
    sourceReferences: ["电影《你好，李焕英》（2021）"],
  }),
  movie({
    id: "movie-cn-cheng-yong",
    filmTitle: "我不是药神",
    characterName: "程勇",
    region: "中国大陆",
    stage: "growth",
    vector: { growth: 9, expression: 7, stability: 6, discernment: 8, adaptability: 9 },
    coreDrive: "核心推动力从个人生计逐步扩大到对他人处境的责任感，并重新衡量风险与价值的关系。",
    actionStyle: "擅长在现实限制中寻找渠道，用务实、快速的组织方式把分散需求连接成行动网络。",
    stressResponse: "压力逼近时先计算自保与成本，可能短暂切断情感，但真实后果会迫使他重新选择立场。",
    relationshipStyle: "关系由共同处境和具体互助建立，信任不是抽象承诺，而是在风险分配中逐渐形成。",
    talentExpression: "能够看见正式路径之外的资源连接，并把个人应变能力发展为解决群体困境的执行力。",
    blindSpot: "容易在早期把交易边界当成全部责任，直到他人的真实代价进入视野才修正判断。",
    turningPoint: "转折在于他不再只问行动是否划算，而开始面对自己有能力时愿意承担到什么程度。",
    matureArc: "成熟方向是让同理心与风险管理并存，建立不依赖个人英雄化的支持和转介路径。",
    shadowArc: "阴影方向是在自保与牺牲之间剧烈摆动，既无法稳定保护自己，也难以建设长期机制。",
    similar: "当适应、成长与辨识维度同时突出时，你与程勇的镜像相似在于能在规则空隙中迅速组织资源，也会因看见具体处境而重新评估最初的利益边界。",
    different: "角色面对医疗可及性和法律风险的极端冲突；现实助人需要尊重专业、合法渠道与自身能力限制。",
    lesson: "把想帮助的事项分成直接行动、专业转介和制度反馈三层，明确每层责任与风险，不让善意只靠个人硬扛。",
    shadow: "如果只能在冷漠和自我牺牲间选择，你可能反复越界后撤退；真正可持续的责任需要伙伴、程序和停止条件。",
    sourceReferences: ["电影《我不是药神》（2018）"],
  }),
  movie({
    id: "movie-cn-lang-ping",
    filmTitle: "夺冠",
    characterName: "郎平",
    region: "中国大陆",
    stage: "growth",
    vector: { growth: 9, expression: 7, stability: 9, discernment: 9, adaptability: 8 },
    coreDrive: "核心推动力是让团队在高标准竞争中持续更新，不把过去荣誉当成拒绝变化的理由。",
    actionStyle: "以训练证据和明确要求推进，同时根据成员差异调整角色，让共同目标拥有多种实现路径。",
    stressResponse: "压力增大时会强化标准和节奏，若沟通不足，容易让团队只感到要求而看不见调整依据。",
    relationshipStyle: "重视共同承担和专业信任，关心常通过训练设计、角色安排与关键时刻的支持表达。",
    talentExpression: "能够把经验权威转成可迭代的方法，也能在集体传统与个体能力之间建立新的配合。",
    blindSpot: "容易把高标准视为默认共同语言，低估不同成员对反馈方式、恢复节奏和意义感的需要。",
    turningPoint: "转折在于她必须让成功经验接受新环境检验，从亲自做到转向帮助不同的人形成整体能力。",
    matureArc: "成熟方向是以清楚标准守住质量，同时把试验、授权和恢复纳入长期竞争力。",
    shadowArc: "阴影方向是用过去成就压缩探索空间，使团队维护荣耀却失去面对新问题的学习速度。",
    similar: "当成长、稳定和辨识维度都较高时，你与郎平的镜像相似在于既能守住质量底线，也愿意为了长期表现更新方法，把个人经验转成团队能力。",
    different: "影片中的竞技环境目标清楚、反馈迅速；你的团队任务可能更模糊，需要先共同定义何为有效成果。",
    lesson: "为团队同时设置结果指标、学习指标和恢复指标，每次复盘都检查三者，避免短期胜负吞掉长期能力建设。",
    shadow: "若标准只剩不可质疑的强度，你可能获得整齐执行，却失去成员主动判断和及时暴露问题的安全空间。",
    sourceReferences: ["电影《夺冠》（2020）"],
  }),

  movie({
    id: "movie-hk-song-zihao",
    filmTitle: "英雄本色",
    characterName: "宋子豪",
    region: "中国香港",
    stage: "instinct",
    vector: { growth: 6, expression: 7, stability: 7, discernment: 6, adaptability: 6 },
    coreDrive: "核心推动力是维护尊严与兄弟承诺，同时渴望从旧有身份中退出并重新建立生活秩序。",
    actionStyle: "行动直接而重承诺，遇到关键关系受损时会迅速把个人安全放到较后的位置。",
    stressResponse: "压力下容易回到以牺牲证明可信的模式，难以相信清楚边界也能表达忠诚和情义。",
    relationshipStyle: "对认可的伙伴高度负责，但关系判断容易落在并肩承担与是否背离的二元标准上。",
    talentExpression: "能够在复杂人际中维持担当，并用实际选择为抽象的承诺赋予具体重量。",
    blindSpot: "容易让过去身份持续规定当下行动，低估退出旧规则需要制度支持和长期距离。",
    turningPoint: "转折来自他必须理解改过不只是个人决心，也需要面对旧关系、家人伤痕和现实后果。",
    matureArc: "成熟方向是把义气转化为可持续的责任，允许拒绝危险要求而不否定关系价值。",
    shadowArc: "阴影方向是不断回到高风险情境证明自己，最终让修复被新的牺牲一次次打断。",
    similar: "当稳定与表达维度处于中高位置时，你与宋子豪的镜像相似在于看重承诺的实际兑现，也希望在关系和身份冲突中保住个人尊严。",
    different: "电影通过类型化冲突放大忠诚选择；现实关系可以借助法律、组织和沟通机制减少个人牺牲。",
    lesson: "面对忠诚请求时先区分支持、包庇和自我伤害，选择既不背离原则又能清楚说明边界的具体回应。",
    shadow: "若总靠承担危险来证明可信，你会让关系只在危机中显得深刻，也难以建立平静、互惠且可长期维持的连接。",
    sourceReferences: ["电影《英雄本色》（1986）"],
  }),
  movie({
    id: "movie-hk-chan-kakweui",
    filmTitle: "警察故事",
    characterName: "陈家驹",
    region: "中国香港",
    stage: "instinct",
    vector: { growth: 6, expression: 9, stability: 4, discernment: 6, adaptability: 9 },
    coreDrive: "核心推动力是迅速阻止眼前风险，并通过亲自行动恢复被破坏的安全和正当秩序。",
    actionStyle: "依靠强烈现场反应和身体投入推进，常在计划尚未完整时就根据变化连续调整。",
    stressResponse: "压力上升会进一步加速，容易把谨慎协作看成拖延，也可能低估行动外溢的代价。",
    relationshipStyle: "对同伴和亲近者有保护意愿，却常让任务优先级压过解释、预告和情绪修复。",
    talentExpression: "擅长在混乱现场快速找到可用路径，并以高适应性把突发障碍转成下一步动作。",
    blindSpot: "容易把愿意冒险等同于有能力承担全部后果，忽略伙伴也需要决定是否进入风险。",
    turningPoint: "转折在于他必须面对行动正当并不自动意味着过程无须约束，关系损耗也是真实结果。",
    matureArc: "成熟方向是保留现场勇气，同时使用预案、协同和停止条件降低不必要的连带风险。",
    shadowArc: "阴影方向是不断依赖更大危机确认价值，使日常秩序和亲密关系长期处在事后修补。",
    similar: "当表达和适应维度较高而稳定度较低时，你与陈家驹的镜像相似在于能对突发变化迅速响应，也愿意直接进入问题而非等待别人处理。",
    different: "动作电影把现场风险和个人能力高度浓缩；现实专业行动更依赖程序、团队授权和风险控制。",
    lesson: "下次快速介入前完成三秒检查：谁授权、谁受影响、何时停止，让敏捷反应与最低必要保护同时启动。",
    shadow: "如果速度持续替代评估，你可能一次次解决眼前危机，却让伙伴为不可预告的风险和长期善后承担额外成本。",
    sourceReferences: ["电影《警察故事》（1985）"],
  }),
  movie({
    id: "movie-hk-yuddy",
    filmTitle: "阿飞正传",
    characterName: "旭仔",
    region: "中国香港",
    stage: "instinct",
    vector: { growth: 5, expression: 7, stability: 2, discernment: 5, adaptability: 8 },
    coreDrive: "核心推动力是摆脱被固定和被遗弃的感受，通过保持流动确认自己仍拥有选择和吸引力。",
    actionStyle: "习惯先靠近再抽离，用节奏变化掌握关系主动，并不断寻找能解释自身来处的新线索。",
    stressResponse: "不安升高时会切断承诺或转移目标，借离开避免暴露依赖和可能再次失去的恐惧。",
    relationshipStyle: "能够迅速制造亲密感，却难以在平稳阶段持续回应对方，把距离当成保护自主的工具。",
    talentExpression: "对场域情绪与个人魅力有敏锐感受，能以独特节奏创造强烈而难忘的存在感。",
    blindSpot: "容易把自由理解为不留下责任，低估自己的靠近和离开会在他人生活中产生连续影响。",
    turningPoint: "转折在于他试图追索身份来源，却仍需面对真正困住自己的不仅是过去，也是回避连接的方式。",
    matureArc: "成熟方向是允许依赖和自主同时存在，用可预期的回应代替反复消失来维护边界。",
    shadowArc: "阴影方向是不断更换关系和地点，却让同一种被遗弃感在每次离开后重新出现。",
    similar: "当适应和表达较高、稳定较低时，你与旭仔的镜像相似在于很重视个人节奏，也能敏锐察觉关系对自由感造成的拉力与限制。",
    different: "角色以疏离和流动承载身份困惑；现实中你可以通过持续支持与专业帮助探索来处，而不必伤害连接。",
    lesson: "当想突然退出时，先说出需要的距离、预计时长和恢复联系的方式，让自主成为边界，而不是让别人承受失联。",
    shadow: "若每次不安都靠离开处理，你可能保住即时控制感，却逐渐失去可以容纳复杂来处和真实脆弱的长期关系。",
    sourceReferences: ["电影《阿飞正传》（1990）"],
  }),
  movie({
    id: "movie-hk-chen-yongren",
    filmTitle: "无间道",
    characterName: "陈永仁",
    region: "中国香港",
    stage: "current",
    vector: { growth: 5, expression: 3, stability: 8, discernment: 10, adaptability: 9 },
    coreDrive: "核心推动力是守住真实身份和职业信念，希望长期隐忍最终能够回到清楚、正当的位置。",
    actionStyle: "依靠高辨识和克制反应生存，在多重信息之间持续判断何时行动、何时隐藏。",
    stressResponse: "长期压力使他提高警觉并压缩情绪出口，容易把独自承担视为保护任务的唯一方式。",
    relationshipStyle: "渴望被理解，却受保密和风险限制，只能在少数安全关系中短暂呈现真实状态。",
    talentExpression: "擅长读取细微信号、维持角色边界，并在信息不完整时保持清楚的核心判断。",
    blindSpot: "容易让任务身份吞没个人生活，低估长期双重状态对身体、信任和自我连续性的侵蚀。",
    turningPoint: "转折来自回归正常生活的希望不断被现实推迟，他必须面对坚持本身也需要安全与见证。",
    matureArc: "成熟方向是让忠诚接受支持系统承接，不把保密误解为所有痛苦都必须独自消化。",
    shadowArc: "阴影方向是把高度警觉固化成常态，即使危险结束也无法相信平静和他人的可靠。",
    similar: "当辨识、适应与稳定维度较高时，你与陈永仁的镜像相似在于能在复杂信息中守住核心任务，也常比别人更早发现环境中的不一致。",
    different: "角色承担极端卧底风险；现实工作即使需要保密，也应有明确授权、监督、支持和退出机制。",
    lesson: "为高压保密任务确认一个合规支持人、一个身体警报指标和一个退出条件，让专业忠诚不等于孤立无援。",
    shadow: "如果长期只允许自己作为功能存在，你可能完成许多关键任务，却越来越难回答离开角色之后自己需要怎样生活。",
    sourceReferences: ["电影《无间道》（2002）"],
  }),
  movie({
    id: "movie-hk-li-qiao",
    filmTitle: "甜蜜蜜",
    characterName: "李翘",
    region: "中国香港",
    stage: "current",
    vector: { growth: 8, expression: 7, stability: 5, discernment: 7, adaptability: 10 },
    coreDrive: "核心推动力是在陌生城市建立经济和身份立足点，同时寻找能被理解和共同前行的关系。",
    actionStyle: "善于发现机会并快速切换角色，用务实行动积累资源，也会根据环境重新安排优先级。",
    stressResponse: "不确定升高时会优先抓住可见的稳定选项，情感需要可能被推迟或转入更隐蔽的位置。",
    relationshipStyle: "既重视现实共同体，也渴望真切共鸣，常在安全、承诺与个人流动之间来回衡量。",
    talentExpression: "能迅速理解新城市的运行方式，把社交敏感度、行动力和资源意识结合起来。",
    blindSpot: "容易认为等条件稳定后再处理情感，却低估长期搁置会让选择由环境惯性替自己完成。",
    turningPoint: "转折来自她发现现实上正确的安排未必能安放全部情感，必须承认两套需求同时存在。",
    matureArc: "成熟方向是让务实规划包含内在愿望，并在选择前清楚告知相关者真实位置和代价。",
    shadowArc: "阴影方向是持续追逐下一份安全感，最终拥有许多立足点却没有一处允许完整停留。",
    similar: "当适应和成长维度突出时，你与李翘的镜像相似在于能够迅速进入新环境、捕捉现实机会，也会认真计算每项选择对未来稳定的影响。",
    different: "角色的迁移经验与城市机遇属于特定时期香港；你的资源、身份和关系约束需要重新盘点。",
    lesson: "做迁移或职业选择时同时列现实收益、情感代价和一年后回看标准，避免只让最紧迫的指标垄断决定。",
    shadow: "如果每次都把真实愿望推到以后，你可能越来越擅长适应外部，却越来越难分辨哪些生活是自己真正想留下的。",
    sourceReferences: ["电影《甜蜜蜜》（1996）"],
  }),
  movie({
    id: "movie-hk-su-lizhen",
    filmTitle: "花样年华",
    characterName: "苏丽珍",
    region: "中国香港",
    stage: "current",
    vector: { growth: 5, expression: 4, stability: 8, discernment: 9, adaptability: 6 },
    coreDrive: "核心推动力是维护自我尊严和关系边界，即使情感复杂，也不愿让受伤决定自己成为怎样的人。",
    actionStyle: "通过克制观察和细致确认推进，很少直接越过边界，而是在接近与退回之间反复衡量。",
    stressResponse: "压力下会进一步收紧表达，以保持体面和控制，却可能让重要感受缺少被处理的出口。",
    relationshipStyle: "重视分寸、理解和共同经验形成的默契，但直接需求常被放在礼貌和风险评估之后。",
    talentExpression: "能够细致辨认关系中的微妙变化，并在混乱中守住不愿复制的行为底线。",
    blindSpot: "容易把不打扰和不越界扩展为不表达，使对方无法参与判断，也让自己长期停在未完成状态。",
    turningPoint: "转折在于她看见共同受伤可以带来理解，却不能自动提供一个既真实又可承担的关系位置。",
    matureArc: "成熟方向是保留边界感，同时为真实感受找到清楚、及时且不伤害他人的表达方式。",
    shadowArc: "阴影方向是把所有复杂情感封存在体面之下，让人生在看似平静中不断积累未完成。",
    similar: "当辨识和稳定维度较高、表达较克制时，你与苏丽珍的镜像相似在于对关系边界非常敏感，也希望自己的选择经得起长期回看。",
    different: "影片以留白放大情感张力；现实关系需要更明确的信息，沉默并不会自动让彼此理解相同。",
    lesson: "遇到不能继续含糊的关系时，分别说清事实、边界和愿望，不要求立即得到结果，但停止让猜测代替双方选择。",
    shadow: "若体面总比真实优先，你可能避免一时冲突，却把长期遗憾、身体紧张和关系误读全部留给自己消化。",
    sourceReferences: ["电影《花样年华》（2000）"],
  }),
  movie({
    id: "movie-hk-sing",
    filmTitle: "少林足球",
    characterName: "阿星",
    region: "中国香港",
    stage: "growth",
    vector: { growth: 10, expression: 9, stability: 5, discernment: 5, adaptability: 8 },
    coreDrive: "核心推动力是让被忽视的能力重新进入现实生活，并相信旧训练可以找到新的公共用途。",
    actionStyle: "以高热情拉起团队，用实验性组合连接不同专长，即使笨拙也愿意先让方案动起来。",
    stressResponse: "受挫时会用更强乐观推动，可能暂时看不见伙伴的羞耻、顾虑和现实准备程度。",
    relationshipStyle: "倾向通过共同梦想快速建立连接，愿意看见别人的长处，也期待大家重新相信自己。",
    talentExpression: "擅长跨领域联想，把看似过时或分散的能力重新组合成有趣且可参与的行动。",
    blindSpot: "容易低估落地所需的训练、规则和资源，只凭感染力不能保证伙伴拥有同等承受能力。",
    turningPoint: "转折来自团队不再只是被理想召集，而是在真实协作中重新找回能力、信任和位置。",
    matureArc: "成熟方向是让创意愿景配上训练计划、角色分工和现实反馈，使热情能够持续。",
    shadowArc: "阴影方向是不断发起新的激动计划，却在枯燥建设阶段失去耐心并留下未完成关系。",
    similar: "当成长和表达维度很高时，你与阿星的镜像相似在于能够看见旧能力的新用途，也善于用热情让灰心的人重新进入尝试。",
    different: "喜剧电影让跨界成功快速显现；现实创新通常需要更长训练、合规检查和多轮失败反馈。",
    lesson: "把一个兴奋点写成四周实验，每周只验证一个关键假设，并让伙伴自行选择投入程度，不用热情替别人承诺。",
    shadow: "如果所有问题都靠鼓舞解决，你可能忽略疲惫、资源和真实分歧，最终让伙伴把你的愿景理解为新的压力来源。",
    sourceReferences: ["电影《少林足球》（2001）"],
  }),
  movie({
    id: "movie-hk-tao-jie",
    filmTitle: "桃姐",
    characterName: "桃姐",
    region: "中国香港",
    stage: "growth",
    vector: { growth: 6, expression: 4, stability: 10, discernment: 7, adaptability: 6 },
    coreDrive: "核心推动力是以日常照料维持他人的生活秩序，同时尽量保留自己的尊严和不添麻烦。",
    actionStyle: "通过细致、重复和低声量的行动回应需要，很少把贡献转成要求别人确认的语言。",
    stressResponse: "身体与环境变化时倾向缩小需求，可能用接受安排掩盖失落，也不愿让亲近者为难。",
    relationshipStyle: "关系建立在长期共同生活的细节里，身份边界看似清楚，情感却早已超过简单职务。",
    talentExpression: "能够记住微小偏好并稳定照料，把不显眼的劳动变成他人生活可靠运行的底层结构。",
    blindSpot: "容易把被照料视为负担别人，因而不主动说出疼痛、害怕和希望参与决定的需要。",
    turningPoint: "转折来自照料方向改变，双方必须重新理解彼此不只是服务与被服务，也是长期情感关系。",
    matureArc: "成熟方向是让给予与接受都保有尊严，把需要说清楚，也允许关系在角色变化后继续更新。",
    shadowArc: "阴影方向是把自我抹去当成体贴，使所有人直到失去之后才看见长期劳动和情感重量。",
    similar: "当稳定维度突出时，你与桃姐的镜像相似在于会用细节和持续行动照顾关系，也常把可靠理解为不需要别人额外操心。",
    different: "角色经历包含长期家务劳动、老年与照护制度处境；你的照料责任和支持资源需要单独评估。",
    lesson: "把照料关系中的给予、接受和决定权分别列出，至少增加一个让照料者也能提出需要、休息和选择的固定节点。",
    shadow: "若体贴只能表现为隐藏需求，你可能让关系长期失去互惠机会，也让旁人无法在还有时间时学习怎样真正支持你。",
    sourceReferences: ["电影《桃姐》（2011）"],
  }),
  movie({
    id: "movie-hk-luo-jiner",
    filmTitle: "岁月神偷",
    characterName: "罗进二",
    region: "中国香港",
    stage: "growth",
    vector: { growth: 8, expression: 5, stability: 7, discernment: 6, adaptability: 8 },
    coreDrive: "核心推动力是理解家庭在变化中的坚持方式，并从孩子视角逐渐学会承接失去与责任。",
    actionStyle: "先以好奇和灵活应对日常，通过观察家人的选择，慢慢把零散经验组织成价值判断。",
    stressResponse: "面对无法控制的变化时会寻找简单解释或可执行小事，以减少无力感带来的冲击。",
    relationshipStyle: "依恋家庭的共同节奏，也会通过模仿、玩笑和行动试探自己在关系中的位置。",
    talentExpression: "能够从平凡物件和生活细节中感受情感意义，并在变化中保留学习与适应能力。",
    blindSpot: "容易以为只要足够听话或努力就能阻止失去，把超出个人能力的结果归到自己身上。",
    turningPoint: "转折来自他逐渐理解成长不等于控制一切，而是带着记忆继续参与现实生活与家庭连接。",
    matureArc: "成熟方向是允许悲伤和行动并存，把对家人的爱转成当下可承担的责任而非自责。",
    shadowArc: "阴影方向是把早期失去变成必须永远坚强的命令，长大后仍不允许自己依赖和哀伤。",
    similar: "当成长与适应维度较高时，你与罗进一的镜像相似在于能够从日常变化里学习，也会用具体小事重新找回对生活的参与感。",
    different: "角色从儿童视角经历家庭经济和生命变化；你可使用的理解能力、支持系统和责任范围并不相同。",
    lesson: "面对无法挽回的变化时，写下不属于你的责任、可以完成的小事和需要共同纪念的部分，避免用自责制造控制感。",
    shadow: "若过早把懂事当成唯一成长方式，你可能很会照顾场面，却难以承认自己也需要安慰、解释和被别人承担一部分。",
    sourceReferences: ["电影《岁月神偷》（2010）", "https://www.filmarchive.gov.hk/sc/web/hkfa/pe-event-2021-mna-fs-film03.html"],
  }),

  movie({
    id: "movie-asia-kim-kiwoo",
    filmTitle: "寄生虫",
    characterName: "金基宇",
    region: "亚洲",
    stage: "instinct",
    vector: { growth: 8, expression: 7, stability: 3, discernment: 8, adaptability: 10 },
    coreDrive: "核心推动力是突破资源和阶层限制，希望凭敏锐观察进入一个看似拥有更多可能的生活位置。",
    actionStyle: "快速读取环境期待，调整身份表达并串联机会，把临时入口逐步扩展为家庭资源。",
    stressResponse: "当伪装面临暴露时会加速控制信息，判断越来越受即时生存压力和侥幸心理影响。",
    relationshipStyle: "重视家庭共同利益，却容易让外部关系变成工具，难以在利益之外建立稳定互信。",
    talentExpression: "擅长捕捉规则未明说的门槛，并能迅速学习符合场域期待的语言与行为方式。",
    blindSpot: "容易把进入优势位置误认为结构已经改变，低估脆弱基础和他人处境反噬的可能。",
    turningPoint: "转折来自精心维持的上升路径被现实裂缝打断，他必须面对适应力无法独自消除结构风险。",
    matureArc: "成熟方向是把敏锐用于识别真实资源和长期路径，不再以欺骗和排除更弱者换取暂时入口。",
    shadowArc: "阴影方向是持续升级伪装与比较，使每次靠近理想生活都同时增加暴露和失控成本。",
    similar: "当适应、辨识和成长维度很高而稳定较低时，你与金基宇的镜像相似在于能迅速读懂陌生场域，也善于抓住别人忽略的进入机会。",
    different: "角色处于尖锐的经济与阶层冲突中；现实选择仍要考虑合法性、他人权益和长期可验证的能力建设。",
    lesson: "面对诱人的捷径时写下入口条件、维持成本和受影响者，优先选择能积累真实能力而非只维持形象的路径。",
    shadow: "若适应力只服务于进入更高位置，你可能越来越会扮演，却没有稳定身份、可信关系和承受失败的现实基础。",
    sourceReferences: ["电影《寄生虫》（2019）"],
  }),
  movie({
    id: "movie-asia-osamu-shibata",
    filmTitle: "小偷家族",
    characterName: "柴田治",
    region: "亚洲",
    stage: "instinct",
    vector: { growth: 5, expression: 6, stability: 5, discernment: 5, adaptability: 9 },
    coreDrive: "核心推动力是用非正式方式拼出归属和日常温暖，即使资源匮乏也希望有人共同生活。",
    actionStyle: "依靠即时应变和关系默契维持家庭运转，常绕开正式规则解决眼前生存问题。",
    stressResponse: "风险逼近时会在保护关系与保护自己之间摇摆，容易用临时解释推迟面对长期后果。",
    relationshipStyle: "亲近建立在共同照料和秘密之上，情感真实，却缺少足够清楚、合法和安全的边界。",
    talentExpression: "能够在边缘处境中创造家庭感，让被忽略的人获得日常关注和共同参与的位置。",
    blindSpot: "容易认为有爱就足以替代程序与权利保障，低估依赖、同意和儿童安全等现实问题。",
    turningPoint: "转折来自非正式家庭面对外部审视，成员必须区分真实情感与并不因此自动正当的行为。",
    matureArc: "成熟方向是让照料接受责任、合法支持和被照料者选择权的共同检验。",
    shadowArc: "阴影方向是把共同秘密当成亲密核心，使成员只能用隐瞒维持归属而无法获得稳定保护。",
    similar: "当适应维度较高而稳定资源有限时，你与柴田治的镜像相似在于能用细小行动创造归属感，也会在正式支持不足时寻找非标准解决办法。",
    different: "角色家庭涉及贫困、违法与儿童权益等复杂处境；现实照料必须优先使用合法、专业和安全的支持路径。",
    lesson: "当温情与规则冲突时，先确认最弱者的安全、同意和长期权益，再寻找能够保留连接而不依赖隐瞒的正式支持。",
    shadow: "如果把被理解的感觉当成全部正当性，你可能看不见权力差异，让真情与伤害在同一关系里长期纠缠。",
    sourceReferences: ["电影《小偷家族》（2018）"],
  }),
  movie({
    id: "movie-asia-lee-jongsu",
    filmTitle: "燃烧",
    characterName: "李钟秀",
    region: "亚洲",
    stage: "instinct",
    vector: { growth: 5, expression: 3, stability: 3, discernment: 8, adaptability: 6 },
    coreDrive: "核心推动力是为模糊生活寻找确定解释，并希望通过理解他人和世界确认自己的存在位置。",
    actionStyle: "长时间观察和积累细节，行动启动较慢，但一旦形成解释就会围绕它持续追索。",
    stressResponse: "不确定升高时容易把零散线索连接成单一叙事，以强烈确信抵消无力与被排除感。",
    relationshipStyle: "渴望靠近，却不擅长直接核对彼此位置，容易在沉默中放大想象、比较和怨怼。",
    talentExpression: "对环境中的空缺和不协调有敏锐感受，具备把隐约经验转成表达素材的潜力。",
    blindSpot: "容易把自己的解释当成唯一真相，忽略事实不足、他人自主和情绪对判断的塑形。",
    turningPoint: "转折来自模糊线索不断触发他的失控感，他必须选择继续核验，还是让猜疑接管行动。",
    matureArc: "成熟方向是容纳暂时不知道，用可验证事实和直接沟通替代不断升级的内在叙事。",
    shadowArc: "阴影方向是让被忽视感与猜疑相互放大，最终用不可逆行动结束自己无法承受的不确定。",
    similar: "当辨识较高、稳定与表达偏低时，你与李钟秀的镜像相似在于会注意别人略过的细节，也常试图为含混经验找到一个能够解释全部的线索。",
    different: "影片刻意保留不确定并强化心理张力；现实判断必须区分可证事实、个人推断和情绪触发。",
    lesson: "当一个解释越来越确定时，主动写下三个反证问题并找当事人或可信伙伴核对，给未知保留合法位置。",
    shadow: "若无法容纳信息空白，你可能用越来越完整的故事封闭现实，也让孤独、嫉妒和无力在未经检验时变成行动依据。",
    sourceReferences: ["电影《燃烧》（2018）"],
  }),
  movie({
    id: "movie-asia-kobayashi-daigo",
    filmTitle: "入殓师",
    characterName: "小林大悟",
    region: "亚洲",
    stage: "current",
    vector: { growth: 8, expression: 5, stability: 8, discernment: 8, adaptability: 8 },
    coreDrive: "核心推动力是重新找到能安放专业感和自我价值的工作，并理解生命告别中的尊严需求。",
    actionStyle: "从不适与观察开始，通过重复练习掌握细节，逐步让陌生工作成为稳定而有意义的技艺。",
    stressResponse: "面对羞耻或他人否定时会隐瞒真实处境，希望先证明价值再承受关系中的解释压力。",
    relationshipStyle: "在亲密关系里需要认可，却因害怕被轻视而延迟坦白，常让沉默增加不必要的隔阂。",
    talentExpression: "能够把克制、程序和身体动作组织成尊重，让复杂情绪获得一个可承受的告别空间。",
    blindSpot: "容易把外部偏见内化为自我怀疑，低估诚实说明工作意义对关系理解的重要性。",
    turningPoint: "转折来自他在反复实践中看见职业的真实价值，开始不再只用社会眼光衡量自己的位置。",
    matureArc: "成熟方向是让专业尊严与关系坦诚同步成长，愿意解释选择并接纳别人需要时间理解。",
    shadowArc: "阴影方向是持续把重要身份藏起来，工作越有意义，亲近者反而越难进入他的真实生活。",
    similar: "当成长、稳定、辨识和适应较均衡时，你与小林大悟的镜像相似在于能从陌生实践中慢慢建立专业感，也会认真对待程序背后的人情重量。",
    different: "角色进入的是特定文化中的殡葬职业；你的转型领域、伦理规范和社会支持条件需要独立了解。",
    lesson: "职业转型时同时记录技能进步、价值意义和关系解释三条线，避免只在工作内部获得确认却让家庭长期缺席。",
    shadow: "如果总要等到自己完全站稳才坦白选择，你可能独自承受本可共享的压力，也让亲近者只能从隐瞒感理解你的工作。",
    sourceReferences: ["电影《入殓师》（2008）"],
  }),
  movie({
    id: "movie-asia-rancho",
    filmTitle: "三傻大闹宝莱坞",
    characterName: "兰彻",
    region: "亚洲",
    stage: "current",
    vector: { growth: 10, expression: 9, stability: 6, discernment: 8, adaptability: 9 },
    coreDrive: "核心推动力是让学习回到理解和创造本身，不愿把排名、身份与恐惧当成教育的唯一方向。",
    actionStyle: "通过提问、实验和幽默打破僵化，用现场验证挑战只靠记忆和权威维持的答案。",
    stressResponse: "面对荒谬规则时会直接反击，可能因确信方法正确而低估他人承担制度后果的差异。",
    relationshipStyle: "鼓励伙伴寻找自己的方向，重视真诚和成长，但有时行动太快，解释和告别不够充分。",
    talentExpression: "擅长把复杂知识转成可体验的问题，并用好奇心恢复团队在压力下失去的学习动力。",
    blindSpot: "容易把个人理解力和勇气当成普遍起点，忽略资源、家庭压力与风险承受能力并不相同。",
    turningPoint: "转折在于他的学习理念必须穿过真实后果，不能只作为聪明反叛，也要成为可持续的选择。",
    matureArc: "成熟方向是把挑战权威与照顾同行者结合，为不同起点的人设计可进入的实践路径。",
    shadowArc: "阴影方向是以自由之名轻视程序和他人顾虑，使创新变成另一种只有强者跟得上的标准。",
    similar: "当成长、表达和适应维度都很高时，你与兰彻的镜像相似在于更愿意理解问题原理，也能用好奇和行动让僵硬环境重新出现可能。",
    different: "喜剧叙事集中呈现教育制度冲突；现实改革需要证据、组织协作和对不同学生风险的保护。",
    lesson: "每次挑战旧做法时，同时准备一个可验证替代方案、一项风险保护和一个让谨慎者参与的低门槛入口。",
    shadow: "若把敏捷理解当成所有人的义务，你可能在反对单一标准时又建立新的优越感，让需要支持的人再次沉默。",
    sourceReferences: ["电影《三傻大闹宝莱坞》（2009）"],
  }),
  movie({
    id: "movie-asia-simin",
    filmTitle: "一次别离",
    characterName: "西敏",
    region: "亚洲",
    stage: "current",
    vector: { growth: 8, expression: 7, stability: 6, discernment: 9, adaptability: 7 },
    coreDrive: "核心推动力是为女儿和自己争取更有发展空间的生活，同时不愿让重要选择无限期拖延。",
    actionStyle: "倾向明确提出改变并推动决定，遇到阻力时会持续要求把含糊立场转成可执行选择。",
    stressResponse: "僵局中会提高决断强度，容易把等待理解为拒绝，也可能低估对方被照料责任牵住的现实。",
    relationshipStyle: "重视共同规划和诚实回应，无法长期接受只有情感承诺却没有行动路径的关系。",
    talentExpression: "能够辨认生活结构中的长期限制，并有勇气让被拖延的问题进入正式讨论。",
    blindSpot: "容易在争取未来时压缩当下复杂性，把多重责任看成对改变意愿的单一检验。",
    turningPoint: "转折来自离开或留下都牵动他人，她必须承认正确方向可能仍伴随无法消除的损失。",
    matureArc: "成熟方向是保持发展诉求，同时把照料、孩子选择和伴侣困境纳入可协商的时间方案。",
    shadowArc: "阴影方向是让僵局不断证明关系已经失败，最后只剩立场对抗而失去共同设计的空间。",
    similar: "当成长、辨识和表达较高时，你与西敏的镜像相似在于能看见生活结构对未来的长期影响，也不愿让关键选择一直停在含糊承诺。",
    different: "角色处于家庭、移居、照护与法律交织的具体处境；你的决定需要按实际责任和可用资源重新评估。",
    lesson: "面对去留僵局时建立共同时间表，分别标出不可延误事项、照料替代方案和孩子参与方式，让分歧获得可操作结构。",
    shadow: "若只用是否立刻行动判断对方诚意，你可能忽略真实束缚，也会让本可分阶段解决的问题被压成一次关系公投。",
    sourceReferences: ["电影《一次别离》（2011）"],
  }),
  movie({
    id: "movie-asia-chihiro",
    filmTitle: "千与千寻",
    characterName: "荻野千寻",
    region: "亚洲",
    stage: "growth",
    vector: { growth: 10, expression: 6, stability: 7, discernment: 8, adaptability: 10 },
    coreDrive: "核心推动力是保护重要关系并找回回家的路径，在陌生规则中逐步建立自己的行动能力。",
    actionStyle: "先观察环境和他人需要，从小任务开始累积信任，再在关键时刻做出清楚而勇敢的选择。",
    stressResponse: "最初会害怕和僵住，但能在得到具体任务后恢复行动，并通过持续参与扩大承受范围。",
    relationshipStyle: "以真诚、记忆和实际帮助建立连接，不急于控制别人，也愿意看见被外表遮住的需要。",
    talentExpression: "擅长在陌生系统中保留辨识力，把善意、观察和适应结合成逐步成长的能力。",
    blindSpot: "容易在刚进入困境时低估自身资源，需要他人提供足够清楚的第一步才能开始行动。",
    turningPoint: "转折来自她一次次完成原本以为做不到的小事，逐渐从被环境推动变成能够做选择的人。",
    matureArc: "成熟方向是带着敏感继续行动，在帮助别人时也记得自己的名字、目标和回家路径。",
    shadowArc: "阴影方向是为了适应强大系统而忘记自身边界，最终只剩符合环境要求的功能身份。",
    similar: "当成长与适应维度很高时，你与荻野千寻的镜像相似在于能够从陌生环境的小任务开始学习，也会在关系需要时展现超出自我预期的勇气。",
    different: "动画以幻想世界承载成长考验；现实陌生环境仍需合法信息、安全支持和可退出的试验边界。",
    lesson: "进入新系统时先确认自己的目标、一个可信向导和一个最小任务，每完成一步就更新规则理解，不用一次证明全部能力。",
    shadow: "如果适应被误解为必须接受所有规则，你可能迅速变得能干，却逐渐忘记哪些要求不合理、哪些选择原本属于自己。",
    sourceReferences: ["电影《千与千寻》（2001）"],
  }),
  movie({
    id: "movie-asia-shimada-kanbei",
    filmTitle: "七武士",
    characterName: "岛田勘兵卫",
    region: "亚洲",
    stage: "growth",
    vector: { growth: 8, expression: 6, stability: 9, discernment: 10, adaptability: 8 },
    coreDrive: "核心推动力是把有限人手组织成能够保护弱者的行动共同体，并让经验服务于现实责任。",
    actionStyle: "先观察地形、资源与人员特点，再分配位置和训练节奏，用清楚准备降低临场混乱。",
    stressResponse: "高压下仍倾向保持全局判断，但可能把个人疲惫和情感需要放在任务完成之后。",
    relationshipStyle: "通过尊重能力、明确职责和亲自承担建立信任，不依赖炫耀身份维持领导位置。",
    talentExpression: "擅长把不同背景的人整合成互补团队，并将抽象勇气转成具体防线与协作程序。",
    blindSpot: "容易把胜利标准放在保护任务上，忽略参与者在完成之后仍需要意义、归属和恢复。",
    turningPoint: "转折来自团队必须从各自技艺转向共同纪律，他也要让领导经验接受现场反馈修正。",
    matureArc: "成熟方向是用判断力创造他人能够发挥的位置，并把撤退、恢复和交接纳入计划。",
    shadowArc: "阴影方向是不断进入需要拯救的局面，让责任感成为无法停下、无法被别人照料的宿命。",
    similar: "当辨识、稳定、成长和适应都较高时，你与岛田勘兵卫的镜像相似在于会先看整体结构，也能把分散能力组织成有顺序的共同动作。",
    different: "影片中的保卫任务具有清楚敌我和紧迫期限；现实团队常有模糊利益，需要更多协商和权责确认。",
    lesson: "启动复杂协作时画出资源、风险、角色和撤退四张小表，让每个人知道怎样贡献、何时求助以及谁负责最终决定。",
    shadow: "若你总承担全局判断，团队可能越来越依赖你的稳定；你也会把被需要误认成唯一位置，难以真正交棒和恢复。",
    sourceReferences: ["电影《七武士》（1954）"],
  }),
  movie({
    id: "movie-asia-geeta-phogat",
    filmTitle: "摔跤吧！爸爸",
    characterName: "吉塔·珀尕",
    region: "亚洲",
    stage: "growth",
    vector: { growth: 10, expression: 7, stability: 8, discernment: 8, adaptability: 9 },
    coreDrive: "核心推动力是把外部强加的训练逐步转成自己的竞技目标，并争取定义能力与未来的权利。",
    actionStyle: "通过高强度重复建立身体能力，在抵触、模仿和自主理解之间逐渐形成个人打法。",
    stressResponse: "压力下可能在服从与反抗之间摆动，既害怕失去支持，也不愿永远按别人方式证明自己。",
    relationshipStyle: "与父亲和教练的关系交织爱、权威和目标，需要不断区分支持、控制与个人选择。",
    talentExpression: "能够把长期纪律、比赛反馈和自我判断结合起来，在规则明确的场域中持续提升。",
    blindSpot: "容易让成绩承担全部自主证明，一旦表现不稳，就难以确认自己是否仍拥有选择价值。",
    turningPoint: "转折来自她必须把训练经验内化成现场判断，从执行别人的路线走向真正为自己比赛。",
    matureArc: "成熟方向是保留纪律和感恩，同时拥有对训练方式、身体边界与人生目标的明确发言权。",
    shadowArc: "阴影方向是不断用更高成绩偿还期待，使竞技成功却无法回答离开评价体系后自己想要什么。",
    similar: "当成长、适应和稳定维度较高时，你与吉塔·珀尕的镜像相似在于能承受长期训练，也会在外部要求中逐渐寻找属于自己的方法和目标。",
    different: "电影以竞技成绩集中呈现代际和性别突破；现实成长也要保护身体、知情选择和多元成功路径。",
    lesson: "把他人期待分成可吸收的训练建议、需要协商的方法和不属于你的目标，分别回应，不让反抗或服从替代判断。",
    shadow: "若所有自主都必须靠获胜证明，你可能无法安全地失败、转向或休息，也会让身体长期承担关系中未解决的权力冲突。",
    sourceReferences: ["电影《摔跤吧！爸爸》（2016）"],
  }),

  movie({
    id: "movie-west-michael-corleone",
    filmTitle: "教父",
    characterName: "迈克尔·柯里昂",
    region: "欧美",
    stage: "instinct",
    vector: { growth: 6, expression: 4, stability: 9, discernment: 10, adaptability: 8 },
    coreDrive: "核心推动力是保护家族并掌握局面，希望用冷静能力阻止外部威胁决定亲近者的命运。",
    actionStyle: "先观察权力关系和薄弱点，再以高度收束的决定改变局势，很少暴露完整意图。",
    stressResponse: "压力越大越压低情感表达，以控制、隔离和不可逆决定恢复安全感与权威。",
    relationshipStyle: "把保护与领导紧密连接，却容易要求亲近者接受信息不对称和由他定义的安全。",
    talentExpression: "擅长长期布局、识别利益网络，并在混乱局面中保持冷静而集中的执行。",
    blindSpot: "容易把控制结果误认为保护关系，忽略恐惧和隐瞒会从内部摧毁原本想守住的家庭。",
    turningPoint: "转折来自他一次次选择以权力解决威胁，原本暂时承担的角色逐渐重塑了全部关系。",
    matureArc: "成熟方向是让保护接受法律、透明和他人自主的约束，不用恐惧换取表面服从。",
    shadowArc: "阴影方向是不断扩大控制来防止失去，最终拥有决定权却失去真实亲密和可信反馈。",
    similar: "当辨识、稳定和适应维度较高而表达偏低时，你与迈克尔的镜像相似在于能在压力下保持冷静，也会本能地承担保护与决策位置。",
    different: "角色身处犯罪家族与暴力权力结构；现实中的保护必须以合法、非伤害和当事人选择为前提。",
    lesson: "重大保护性决定前询问三件事：对方是否知情、是否同意、是否有更少伤害的路径，防止责任感滑向控制。",
    shadow: "若你只相信自己掌握全局，伙伴会因害怕或无从参与而停止提供真实信息，你也会在错误发生前失去纠偏机会。",
    sourceReferences: ["电影《教父》（1972）"],
  }),
  movie({
    id: "movie-west-maximus",
    filmTitle: "角斗士",
    characterName: "马克西姆斯",
    region: "欧美",
    stage: "instinct",
    vector: { growth: 6, expression: 7, stability: 9, discernment: 8, adaptability: 7 },
    coreDrive: "核心推动力是守护荣誉、家人记忆与正当秩序，在被剥夺身份后仍寻找能够行动的位置。",
    actionStyle: "依靠纪律、现场判断和团队信任推进，即使环境剧变，也会迅速重新组织可用力量。",
    stressResponse: "巨大失去会收束为复仇和任务专注，使他能继续行动，却减少处理悲伤的其他路径。",
    relationshipStyle: "通过共同承担和战斗纪律建立信任，尊重实际能力，也愿意把自己的安全与团队绑定。",
    talentExpression: "具备稳定领导、风险判断和现场组织能力，能够让陌生人在高压中形成共同节奏。",
    blindSpot: "容易让正义目标承载全部生命意义，忽略复仇完成之外仍需要面对的自我与关系。",
    turningPoint: "转折来自失去原有身份后，他把个人悲痛与公共秩序连接，行动不再只有即时生存。",
    matureArc: "成熟方向是保留勇气和原则，同时让悲伤、伙伴选择与更长远的修复进入行动。",
    shadowArc: "阴影方向是只允许自己作为战士存在，让每一次伤痛都变成下一场必须赢下的对抗。",
    similar: "当稳定、辨识和表达维度较高时，你与马克西姆斯的镜像相似在于压力越大越能守住行动纪律，也愿意为共同安全承担清楚责任。",
    different: "史诗电影把冲突置于暴力与帝国权力中；现实坚持原则应优先使用法律、协商和非伤害路径。",
    lesson: "当正义感推动你进入对抗时，先定义希望恢复的秩序、可接受手段和结束条件，不让报复感接管全部目标。",
    shadow: "若所有痛苦都通过战斗处理，你可能获得强大行动力，却无法在无需战斗的关系中表达失去、依赖和继续生活的愿望。",
    sourceReferences: ["电影《角斗士》（2000）"],
  }),
  movie({
    id: "movie-west-furiosa",
    filmTitle: "疯狂的麦克斯4：狂暴之路",
    characterName: "弗瑞奥萨",
    region: "欧美",
    stage: "instinct",
    vector: { growth: 8, expression: 7, stability: 6, discernment: 9, adaptability: 10 },
    coreDrive: "核心推动力是帮助受控制者获得选择和安全，并为自己寻找能够重新扎根的正当方向。",
    actionStyle: "以清楚目标、路线判断和快速应变推进，遇到突变时能立刻重新配置资源与伙伴位置。",
    stressResponse: "高压中进一步压缩语言和情绪，只留下任务动作，可能独自承担超出身体容量的风险。",
    relationshipStyle: "信任通过共同选择和实际保护建立，尊重伙伴能力，不要求别人只扮演被拯救者。",
    talentExpression: "擅长在资源匮乏和追击压力中保持方向，把个人决断与团队互助组织成连续行动。",
    blindSpot: "容易把安全想象成遥远目的地，低估真正可持续的改变有时来自重构当下权力关系。",
    turningPoint: "转折来自原定归宿不再存在，她必须把逃离思维转成返回、联合和重新分配资源的判断。",
    matureArc: "成熟方向是让解救行动走向共同治理，既保留锋利执行，也建立后续秩序与恢复。",
    shadowArc: "阴影方向是永远在逃离和救援中证明价值，无法相信自己也可以停下、被支持和共同生活。",
    similar: "当适应、辨识和成长维度很高时，你与弗瑞奥萨的镜像相似在于能在剧烈变化中保持行动目标，也会主动为受限制者创造更多选择。",
    different: "电影处于极端废土与暴力秩序；现实解困必须重视合法资源、专业支持和受助者自主决定。",
    lesson: "制定脱困计划时同时准备离开路径、途中补给和新秩序安排，并让所有参与者对风险与目标拥有真实发言权。",
    shadow: "若你总以救援者身份进入关系，可能忽略自己的损耗，也可能在别人恢复自主后难以找到不靠危机维持的个人位置。",
    sourceReferences: ["电影《疯狂的麦克斯4：狂暴之路》（2015）"],
  }),
  movie({
    id: "movie-west-forrest-gump",
    filmTitle: "阿甘正传",
    characterName: "福瑞斯特·甘",
    region: "欧美",
    stage: "current",
    vector: { growth: 8, expression: 5, stability: 9, discernment: 4, adaptability: 8 },
    coreDrive: "核心推动力是忠实回应眼前承诺，以持续行动和朴素关心维持与重要之人的连接。",
    actionStyle: "不在复杂推演中停留太久，倾向接受明确任务并反复做到，在变化中保持基本节奏。",
    stressResponse: "压力下会继续执行熟悉动作或移动，让身体节奏承接难以解释的失落与混乱。",
    relationshipStyle: "关系投入稳定直接，不擅长策略性表达，却会长期记得承诺并以行动保持在场。",
    talentExpression: "能够减少无谓内耗，把注意力放在可完成的一步，并凭连续性产生超出预期的积累。",
    blindSpot: "容易接受他人设定的方向，辨识复杂利益和保护自身边界的能力需要额外支持。",
    turningPoint: "转折来自一次次人生变化并未改变他对重要关系的基本回应，但经验逐渐增加了理解层次。",
    matureArc: "成熟方向是保留真诚与连续行动，同时建立信息核对和自主选择的保护机制。",
    shadowArc: "阴影方向是把服从清楚指令当成安全，因而在复杂关系中容易被利用或忽略自身需要。",
    similar: "当稳定、成长和适应维度较高时，你与福瑞斯特的镜像相似在于愿意把承诺落实为长期行动，也能在环境变化时继续完成眼前一步。",
    different: "电影以寓言化方式让个人穿过多段历史事件；现实选择需要更主动地核对信息、能力和他人动机。",
    lesson: "继续发挥行动优势，同时为重大请求增加一次事实核验和一位可信伙伴复核，让坚持建立在知情选择之上。",
    shadow: "若只凭善意和执行力回应世界，你可能完成很多别人交付的任务，却迟迟没有机会辨认哪些方向真正属于自己。",
    sourceReferences: ["电影《阿甘正传》（1994）"],
  }),
  movie({
    id: "movie-west-katherine-johnson",
    filmTitle: "隐藏人物",
    characterName: "凯瑟琳·约翰逊",
    region: "欧美",
    stage: "current",
    vector: { growth: 9, expression: 6, stability: 9, discernment: 10, adaptability: 8 },
    coreDrive: "核心推动力是让精确能力获得应有使用空间，并以可靠成果穿透制度偏见设置的限制。",
    actionStyle: "通过计算、复核和清楚呈现推进，在规则阻碍工作时也会指出其真实成本与不合理处。",
    stressResponse: "高压中进一步依赖专业准确保护位置，可能把愤怒和疲惫推迟到任务完成之后处理。",
    relationshipStyle: "重视基于能力的尊重与合作，也需要伙伴理解制度障碍并共同承担改变责任。",
    talentExpression: "能够在复杂系统中保持高精度，把抽象计算转成团队可用于关键决策的可靠依据。",
    blindSpot: "容易因为必须证明专业而过度承担，仿佛只有零失误才有资格要求公平环境。",
    turningPoint: "转折来自她的能力被关键任务需要，制度也必须面对排斥做法正在直接损害共同目标。",
    matureArc: "成熟方向是让卓越能力与制度倡议并行，不再把克服障碍的全部成本留给受影响者。",
    shadowArc: "阴影方向是长期用超额表现换取基本承认，成功越大，身体和关系承受的隐形成本越高。",
    similar: "当辨识、稳定和成长维度很高时，你与凯瑟琳·约翰逊的镜像相似在于会用准确结果建立信任，也能看见程序细节怎样影响整体任务。",
    different: "电影角色基于特定历史人物与美国种族隔离环境；你的制度障碍和行动权限需要按现实证据判断。",
    lesson: "记录阻碍不仅如何影响个人，也如何损害共同产出，再联合有权限者提出具体流程修改，避免只靠个人额外努力补偿。",
    shadow: "若每次不公平都用更完美表现回应，你可能让组织享受成果却无需改变，也会逐渐无法容忍自己正常的学习与失误。",
    sourceReferences: ["电影《隐藏人物》（2016）", "NASA《Katherine Johnson Biography》"],
  }),
  movie({
    id: "movie-west-will-hunting",
    filmTitle: "心灵捕手",
    characterName: "威尔·亨廷",
    region: "欧美",
    stage: "current",
    vector: { growth: 9, expression: 7, stability: 3, discernment: 10, adaptability: 8 },
    coreDrive: "核心推动力是保护自己不再被伤害，同时渴望能力、关系和未来不被早期经历永久限制。",
    actionStyle: "用极快理解和尖锐判断掌握场面，一旦感觉被看穿，就会转向攻击、离开或降低投入。",
    stressResponse: "压力触发时倾向先否定关系价值，以聪明和嘲讽恢复控制，避免暴露需要与害怕失去。",
    relationshipStyle: "能形成深厚连接，却会反复测试对方是否可靠，并在真正靠近时制造退出理由。",
    talentExpression: "具有强大抽象辨识和学习速度，能迅速发现问题结构，也能看见语言中的漏洞。",
    blindSpot: "容易把看穿别人当成已经理解自己，用智力优势避开需要时间、重复和脆弱参与的成长。",
    turningPoint: "转折来自安全关系没有按预期离开或反击，他开始允许过去创伤不再决定全部未来选择。",
    matureArc: "成熟方向是让辨识力服务于探索而非防御，练习在不确定关系中持续出现并接受支持。",
    shadowArc: "阴影方向是不断证明自己比规则和他人聪明，却让每条可能改变生活的路径都在靠近前被摧毁。",
    similar: "当辨识与成长维度很高而稳定较低时，你与威尔的镜像相似在于学习速度快、能迅速识别问题核心，也对控制和评价格外敏感。",
    different: "角色的防御与创伤经历紧密相关；现实相似感不能用于自我诊断，具体困难应由个人经验和专业支持判断。",
    lesson: "当你准备靠聪明结束一段重要对话时，先停下说出一个事实感受和一个小请求，观察关系是否真的只能以防御处理。",
    shadow: "若辨识力持续只用于证明别人不可信，你可能避免再次受伤，也同时切断了被理解、被挑战和共同成长的现实机会。",
    sourceReferences: ["电影《心灵捕手》（1997）"],
  }),
  movie({
    id: "movie-west-andy-dufresne",
    filmTitle: "肖申克的救赎",
    characterName: "安迪·杜弗兰",
    region: "欧美",
    stage: "growth",
    vector: { growth: 9, expression: 4, stability: 10, discernment: 10, adaptability: 8 },
    coreDrive: "核心推动力是保存内在自由与未来可能，即使处境长期封闭，也不让环境定义全部自我。",
    actionStyle: "以耐心、专业和隐蔽的长期步骤推进，善于把微小资源积累成改变处境的完整路径。",
    stressResponse: "压力下更加克制和独立，很少暴露计划与脆弱，因此也可能把可获得的支持排除在外。",
    relationshipStyle: "通过可靠帮助和长期一致建立信任，不轻易表露，但会为少数重要伙伴创造实际机会。",
    talentExpression: "擅长长期规划、制度理解和资源转化，能在高度限制中保留精确而持续的行动线。",
    blindSpot: "容易让自我保护变成过度封闭，伙伴只能看见平静能力，却难以知道他正在承受什么。",
    turningPoint: "转折来自长期准备终于达到可以行动的条件，他把希望从内在信念转成具体而可执行的出口。",
    matureArc: "成熟方向是让耐力与连接并存，在保护计划的同时保留求助、见证和共同未来的位置。",
    shadowArc: "阴影方向是把所有生命都投入遥远出口，长期不允许当下出现任何可被别人触碰的真实需要。",
    similar: "当稳定、辨识和成长维度很高时，你与安迪的镜像相似在于能够把漫长目标拆成连续步骤，也能在外部限制中保存自己的判断标准。",
    different: "角色处于监禁与制度暴力的极端环境；现实长期计划通常可以更透明地使用法律、伙伴和专业资源。",
    lesson: "为长期目标同时设置隐私边界和支持边界，明确哪些信息必须保护、哪些困难可以让可信伙伴参与，避免把独立推成孤立。",
    shadow: "若希望只能存在于遥远未来，你可能忽视当下身体、关系和小幅改善，让坚持成为不能暂停也不能被看见的漫长消耗。",
    sourceReferences: ["电影《肖申克的救赎》（1994）"],
  }),
  movie({
    id: "movie-west-erin-brockovich",
    filmTitle: "永不妥协",
    characterName: "艾琳·布罗克维奇",
    region: "欧美",
    stage: "growth",
    vector: { growth: 9, expression: 10, stability: 6, discernment: 8, adaptability: 9 },
    coreDrive: "核心推动力是让被忽略的伤害获得承认，并用实际调查证明普通人的经验值得进入公共程序。",
    actionStyle: "以直接沟通、密集走访和持续追问推进，能把个人信任与分散材料连接成行动证据。",
    stressResponse: "遭遇轻视时会提高强度并加倍投入，容易把休息和协作提醒听成对能力的再次怀疑。",
    relationshipStyle: "通过真诚站在当事人一边建立信任，但工作投入可能挤压亲密关系的时间与可预期性。",
    talentExpression: "擅长让抽象文件重新连接到具体生活，用表达勇气推动专业系统正视被忽略的信息。",
    blindSpot: "容易认为只有亲自不断追进度才能保护案件，低估分工、程序和个人恢复对长期行动的重要性。",
    turningPoint: "转折来自她的非传统能力产生关键价值，也必须学习让热情进入专业协作和证据规则。",
    matureArc: "成熟方向是把直觉、人际信任与严谨程序结合，使倡议不依赖单个人持续超负荷。",
    shadowArc: "阴影方向是不断用更大投入反击偏见，赢得公共结果却让私人生活和身体长期承担代价。",
    similar: "当表达、成长和适应维度很高时，你与艾琳的镜像相似在于敢于直接进入被忽视的问题，也能通过真实接触发现纸面材料之外的重要线索。",
    different: "角色基于特定法律案件与职业环境；现实调查应遵守隐私、授权、证据程序和专业职责边界。",
    lesson: "把倡议任务分成关系沟通、证据整理和专业判断三条线，为每条线找到合适负责者，让勇气获得制度放大。",
    shadow: "若所有质疑都只能靠个人超额劳动回应，你可能使团队习惯由你补洞，也让自身价值长期绑定在不停战斗和证明之上。",
    sourceReferences: ["电影《永不妥协》（2000）"],
  }),
  movie({
    id: "movie-west-frodo-baggins",
    filmTitle: "指环王：护戒使者",
    characterName: "弗罗多·巴金斯",
    region: "欧美",
    stage: "growth",
    vector: { growth: 9, expression: 5, stability: 7, discernment: 7, adaptability: 9 },
    coreDrive: "核心推动力是保护家园和伙伴，愿意承担一个自己并未主动追求却无法忽视的长期责任。",
    actionStyle: "从谨慎出发，在伙伴支持和沿途经验中逐步扩大行动范围，遇到风险时持续寻找前路。",
    stressResponse: "责任越重越倾向独自承担，害怕负担伤害伙伴，却因此更容易受孤立、怀疑和诱惑影响。",
    relationshipStyle: "珍视忠诚陪伴，也需要学习相信伙伴不仅能同行，还能共同承受信息、恐惧和决定。",
    talentExpression: "具备在巨大压力中保持善意和目标感的能力，能让不同伙伴围绕共同责任建立连接。",
    blindSpot: "容易把任务归属理解为必须独自完成，低估秘密负担会削弱判断并伤害最可信的关系。",
    turningPoint: "转折来自责任对身心影响不断加深，他必须反复选择是封闭自己，还是允许伙伴真正靠近。",
    matureArc: "成熟方向是承认勇气包含求助和交棒，让长期使命由共同体而非单一意志承接。",
    shadowArc: "阴影方向是与任务过度融合，最终无法区分保护目标、控制负担和自己真正需要的生活。",
    similar: "当成长与适应维度较高、稳定居中时，你与弗罗多的镜像相似在于愿意为重要目标走入陌生处境，也会认真对待责任对伙伴造成的影响。",
    different: "奇幻电影把道德压力外化为特殊物件与远征；现实责任通常可以拆分、授权并接受专业支持。",
    lesson: "为沉重任务设立同行者、交棒点和身体警报，提前约定何时必须共享信息，防止保护伙伴变成把他们排除在外。",
    shadow: "若责任只能由你秘密承受，你可能越来越难相信任何帮助，也让任务逐渐重塑全部身份、关系和对未来的想象。",
    sourceReferences: ["电影《指环王：护戒使者》（2001）"],
  }),
];
